// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.ImportOrders</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class ImportOrdersRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<OrderImportTableTypeRequest> Orders { get; init; }
}

public readonly record struct ImportOrdersInput(
    IReadOnlyList<OrderImportTableType> Orders
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct ImportOrdersResultSet1Result(
    int ImportedOrders
);

public sealed class ImportOrdersResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<ImportOrdersResultSet1Result> Result { get; init; } = Array.Empty<ImportOrdersResultSet1Result>();
}

internal static class ImportOrdersRequestMapper
{
    public static async ValueTask<ImportOrdersInput> ToInputAsync(ImportOrdersRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new ImportOrdersRequest();
        IReadOnlyList<OrderImportTableType>? Orders = OrderImportTableTypeRequest.ToTableTypes(request.Orders);
        if (!HasValue(Orders))
        {
            throw new InvalidOperationException("Parameter @Orders must be supplied by the request or a configured binding.");
        }

        return new ImportOrdersInput(
            Orders!
        );
    }

    public static ValueTask<ImportOrdersInput> ToInputAsync(ImportOrdersRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class ImportOrdersPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Orders", System.Data.DbType.Object, null, false, false, "sample.OrderImportTableType"),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "ImportedOrders"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new ImportOrdersResultSet1Result(o0 < 0 ? default(int) : r.GetInt32(o0))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new ImportOrdersResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (ImportOrdersResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (ImportOrdersResultSet1Result)o).ToList() : Array.Empty<ImportOrdersResultSet1Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (ImportOrdersInput)state!;
			{ var prm = cmd.Parameters["@Orders"]; var source = input.Orders; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "sample.OrderImportTableType"; } }
		}
		return new ProcedureExecutionPlan(
			"[sample].[ImportOrders]", parameters, resultSets, OutputFactory, AggregateFactory, Binder, enableParameterBinding: false);
	}
}

/// <summary>Convenience extension for executing '[sample].[ImportOrders]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class ImportOrdersExtensions
{
	public static async Task<ImportOrdersResult> ImportOrdersAsync(this IXtraqDbContext db, ImportOrdersRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await ImportOrdersRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await ImportOrdersAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<ImportOrdersResult> ImportOrdersAsync(this IXtraqDbContext db, ImportOrdersInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await ImportOrdersProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, ImportOrdersInput input, Func<ImportOrdersResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await ImportOrdersProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, ImportOrdersInput input, Func<ImportOrdersResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, ImportOrdersRequest request, Func<ImportOrdersResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await ImportOrdersRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		await StreamResultResultSet1Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
		return;
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, ImportOrdersRequest request, Func<ImportOrdersResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class ImportOrdersProcedure
{
	public const string Name = "[sample].[ImportOrders]";
	public static Task<ImportOrdersResult> ExecuteAsync(DbConnection connection, ImportOrdersInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<ImportOrdersResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, ImportOrdersInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<ImportOrdersResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, ImportOrdersInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<ImportOrdersResult>(interceptorProvider, bindingProvider, connection, ImportOrdersPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, ImportOrdersInput input, Func<ImportOrdersResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, ImportOrdersInput input, Func<ImportOrdersResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, ImportOrdersInput input, Func<ImportOrdersResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "ImportedOrders");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new ImportOrdersResultSet1Result(o0 < 0 ? default(int) : reader.GetInt32(o0));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, ImportOrdersPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, ImportOrdersInput input, Func<ImportOrdersResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, ImportOrdersInput input, Func<ImportOrdersResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
