// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Sample.OrderImportTableType</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record OrderImportTableType : ITableType
{
    public string UserAlias { get; init; } = string.Empty;
    public string OrderNumber { get; init; } = string.Empty;
    public decimal TotalAmount { get; init; }
    public string Currency { get; init; } = string.Empty;
    public DateTime PlacedAtUtc { get; init; }
    public string? Metadata { get; init; }

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public OrderImportTableType() { }

	public static OrderImportTableType Create(
        string UserAlias,
        string OrderNumber,
        decimal TotalAmount,
        string Currency,
        DateTime PlacedAtUtc,
        string? Metadata
    ) =>
	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
	new OrderImportTableType
	{
        UserAlias = UserAlias,
        OrderNumber = OrderNumber,
        TotalAmount = TotalAmount,
        Currency = Currency,
        PlacedAtUtc = PlacedAtUtc,
        Metadata = Metadata
    };
	#pragma warning restore CS0612, CS0618

	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class OrderImportTableTypeBuilder
	{
        private string _UserAlias = string.Empty;
        private string _OrderNumber = string.Empty;
        private decimal _TotalAmount;
        private string _Currency = string.Empty;
        private DateTime _PlacedAtUtc;
        private string? _Metadata;
        public OrderImportTableTypeBuilder WithUserAlias(string value) { _UserAlias = value; return this; }
        public OrderImportTableTypeBuilder WithOrderNumber(string value) { _OrderNumber = value; return this; }
        public OrderImportTableTypeBuilder WithTotalAmount(decimal value) { _TotalAmount = value; return this; }
        public OrderImportTableTypeBuilder WithCurrency(string value) { _Currency = value; return this; }
        public OrderImportTableTypeBuilder WithPlacedAtUtc(DateTime value) { _PlacedAtUtc = value; return this; }
        public OrderImportTableTypeBuilder WithMetadata(string? value) { _Metadata = value; return this; }
        public OrderImportTableType Build()
        {
			#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
			var result = new OrderImportTableType
            {
                UserAlias = _UserAlias,
                OrderNumber = _OrderNumber,
                TotalAmount = _TotalAmount,
                Currency = _Currency,
                PlacedAtUtc = _PlacedAtUtc,
                Metadata = _Metadata
            };
			#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

/// <summary>
/// Minimal API request row mirroring the SQL table type <c>Sample.OrderImportTableType</c> with DataAnnotations metadata.
/// </summary>
public sealed record OrderImportTableTypeRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(120)]
    public string UserAlias { get; init; }
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(40)]
    public string OrderNumber { get; init; }
    public decimal TotalAmount { get; init; }
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(3)]
    public string Currency { get; init; }
    public DateTime PlacedAtUtc { get; init; }
    public string? Metadata { get; init; }

	internal OrderImportTableType ToTableType()
		=> OrderImportTableType.Create(
            UserAlias,
            OrderNumber,
            TotalAmount,
            Currency,
            PlacedAtUtc,
            Metadata
        );

	internal static System.Collections.Generic.IReadOnlyList<OrderImportTableType>? ToTableTypes(System.Collections.Generic.IReadOnlyList<OrderImportTableTypeRequest>? source)
	{
		if (source is null) return null;
		if (source.Count == 0) return System.Array.Empty<OrderImportTableType>();
		var buffer = new OrderImportTableType[source.Count];
		for (var i = 0; i < source.Count; i++)
		{
			var row = source[i];
			if (row is null)
			{
				throw new System.InvalidOperationException("Table type rows cannot contain null entries.");
			}

			buffer[i] = row.ToTableType();
		}

		return buffer;
	}
}
