// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
#if XTRAQ_API_MODE_MINIMAL
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
#endif

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.OrderListByUserAsJson</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
#if XTRAQ_API_MODE_MINIMAL
/// <summary>
/// Request DTO for Minimal API / external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class OrderListByUserAsJsonRequest
{
    public int UserId { get; init; }
}
#endif

public readonly record struct OrderListByUserAsJsonInput(
    int UserId
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct OrderListByUserAsJsonResultSet1PaymentsResult(
    Guid PaymentId,
    string Gateway,
    decimal Amount,
    DateTime? CapturedAtUtc,
    string? FailureReason
);
public readonly record struct OrderListByUserAsJsonResultSet1Result(
    int OrderId,
    string OrderNumber,
    string Status,
    decimal TotalAmount,
    string Currency,
    DateTime PlacedAtUtc,
    DateTime? RequiredAtUtc,
    System.Collections.Generic.List<OrderListByUserAsJsonResultSet1PaymentsResult> Payments
);

public sealed class OrderListByUserAsJsonResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public OrderListByUserAsJsonResultSet1Result? Result { get; init; } = null;
	/// <summary>
	/// Raw JSON payload captured for result set <c>ResultSet1</c>.
	/// </summary>
	public string? ResultRawJson { get; init; } = null;
}

#if XTRAQ_API_MODE_MINIMAL
internal static class OrderListByUserAsJsonRequestMapper
{
    public static async ValueTask<OrderListByUserAsJsonInput> ToInputAsync(OrderListByUserAsJsonRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new OrderListByUserAsJsonRequest();
        int? UserId = request.UserId;
        if (!HasValue(UserId))
        {
            throw new InvalidOperationException("Parameter @UserId must be supplied by the request or a configured binding.");
        }

        return new OrderListByUserAsJsonInput(
            UserId ?? default
        );
    }

    public static ValueTask<OrderListByUserAsJsonInput> ToInputAsync(OrderListByUserAsJsonRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}
#endif

internal static partial class OrderListByUserAsJsonPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@UserId", System.Data.DbType.Int32, null, false, false),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>();
                var __sb = new System.Text.StringBuilder();
                while (await r.ReadAsync(ct).ConfigureAwait(false))
                {
                    if (!r.IsDBNull(0))
                    {
                        __sb.Append(r.GetString(0));
                    }
                }
                var __raw = __sb.Length > 0 ? __sb.ToString() : null;
                var __items = new System.Collections.Generic.List<OrderListByUserAsJsonResultSet1Result>();
                if (__raw != null)
                {
                    try
                    {
                        var __parsed = System.Text.Json.JsonSerializer.Deserialize<OrderListByUserAsJsonResultSet1Result?>(__raw, JsonSupport.Options);
                        if (__parsed is { } __value)
                        {
                            __items.Add(__value);
                        }
                    }
                    catch
                    {
                    }
                }
                list.Add(JsonResultEnvelope<OrderListByUserAsJsonResultSet1Result>.Create(__items, __raw));
                return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new OrderListByUserAsJsonResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 && rows0.Length > 0 && rows0[0] is JsonResultEnvelope<OrderListByUserAsJsonResultSet1Result> env0 && env0.TryGetFirst(out var value0) ? value0 : (OrderListByUserAsJsonResultSet1Result?)null,
				ResultRawJson = rs.Length > 0 && rs[0] is object[] rows0_raw && rows0_raw.Length > 0 && rows0_raw[0] is JsonResultEnvelope<OrderListByUserAsJsonResultSet1Result> env0_raw ? env0_raw.RawJson : null
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (OrderListByUserAsJsonInput)state!;
			cmd.Parameters["@UserId"].Value = input.UserId;
		}
		return new ProcedureExecutionPlan(
			"[sample].[OrderListByUserAsJson]", parameters, resultSets, OutputFactory, AggregateFactory, Binder, enableParameterBinding: false);
	}
}

/// <summary>Convenience extension for executing '[sample].[OrderListByUserAsJson]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class OrderListByUserAsJsonExtensions
{
#if XTRAQ_API_MODE_MINIMAL
    public static async Task<OrderListByUserAsJsonResult> OrderListByUserAsJsonAsync(this IXtraqDbContext db, OrderListByUserAsJsonRequest request, CancellationToken cancellationToken = default)
    {
        var bindingProvider = db as IXtraqParameterBindingProvider;
        var input = await OrderListByUserAsJsonRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
        return await OrderListByUserAsJsonAsync(db, input, cancellationToken).ConfigureAwait(false);
    }
#endif

	public static async Task<OrderListByUserAsJsonResult> OrderListByUserAsJsonAsync(this IXtraqDbContext db, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await OrderListByUserAsJsonProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

#if XTRAQ_API_MODE_MINIMAL
/// <summary>Minimal API extension for '[sample].[OrderListByUserAsJson]'.</summary>
public static class OrderListByUserAsJsonRouteHandlerBuilderExtensions
{
    public static RouteHandlerBuilder WithOrderListByUserAsJsonProcedure(this RouteHandlerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithProcedure<OrderListByUserAsJsonRequest, OrderListByUserAsJsonResult>(
            static pipeline => pipeline.WithExecutor(
                static async ValueTask<OrderListByUserAsJsonResult> (dbContext, request, cancellationToken) =>
                {
                    var bindingProvider = dbContext as IXtraqParameterBindingProvider;
                    var input = await OrderListByUserAsJsonRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
                    return await OrderListByUserAsJsonExtensions.OrderListByUserAsJsonAsync(dbContext, input, cancellationToken).ConfigureAwait(false);
                }));
    }
}
#endif

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class OrderListByUserAsJsonProcedure
{
	public const string Name = "[sample].[OrderListByUserAsJson]";
	public static Task<OrderListByUserAsJsonResult> ExecuteAsync(DbConnection connection, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<OrderListByUserAsJsonResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<OrderListByUserAsJsonResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<OrderListByUserAsJsonResult>(interceptorProvider, bindingProvider, connection, OrderListByUserAsJsonPlan.Instance, input, cancellationToken);
	}

}
