// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
#if XTRAQ_API_MODE_MINIMAL
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
#endif

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.OrderStatusReport</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
#if XTRAQ_API_MODE_MINIMAL
/// <summary>
/// Request DTO for Minimal API / external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class OrderStatusReportRequest
{
    public DateTime FromUtc { get; init; }
    public DateTime ToUtc { get; init; }
}
#endif

public readonly record struct OrderStatusReportInput(
    DateTime FromUtc,
    DateTime ToUtc
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct OrderStatusReportResultSet1Result(
    string Status,
    long? Orders,
    decimal? TotalAmount,
    decimal? AverageAmount,
    DateTime? LastPlacedAtUtc
);

public sealed class OrderStatusReportResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<OrderStatusReportResultSet1Result> Result { get; init; } = Array.Empty<OrderStatusReportResultSet1Result>();
}

#if XTRAQ_API_MODE_MINIMAL
internal static class OrderStatusReportRequestMapper
{
    public static async ValueTask<OrderStatusReportInput> ToInputAsync(OrderStatusReportRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new OrderStatusReportRequest();
        DateTime? FromUtc = request.FromUtc;
        if (!HasValue(FromUtc))
        {
            throw new InvalidOperationException("Parameter @FromUtc must be supplied by the request or a configured binding.");
        }
        DateTime? ToUtc = request.ToUtc;
        if (!HasValue(ToUtc))
        {
            throw new InvalidOperationException("Parameter @ToUtc must be supplied by the request or a configured binding.");
        }

        return new OrderStatusReportInput(
            FromUtc ?? default,
            ToUtc ?? default
        );
    }

    public static ValueTask<OrderStatusReportInput> ToInputAsync(OrderStatusReportRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}
#endif

internal static partial class OrderStatusReportPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@FromUtc", System.Data.DbType.DateTime2, null, false, false),
            new("@ToUtc", System.Data.DbType.DateTime2, null, false, false),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "Status"); int o1=ReaderUtil.TryGetOrdinal(r, "Orders"); int o2=ReaderUtil.TryGetOrdinal(r, "TotalAmount"); int o3=ReaderUtil.TryGetOrdinal(r, "AverageAmount"); int o4=ReaderUtil.TryGetOrdinal(r, "LastPlacedAtUtc"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new OrderStatusReportResultSet1Result(o0 < 0 ? string.Empty : (r.IsDBNull(o0) ? string.Empty : r.GetString(o0)), o1 < 0 ? null : (r.IsDBNull(o1) ? null : (long?)r.GetInt64(o1)), o2 < 0 ? null : (r.IsDBNull(o2) ? null : (decimal?)r.GetDecimal(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : (decimal?)r.GetDecimal(o3)), o4 < 0 ? null : (r.IsDBNull(o4) ? null : (DateTime?)r.GetDateTime(o4)))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new OrderStatusReportResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (OrderStatusReportResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (OrderStatusReportResultSet1Result)o).ToList() : Array.Empty<OrderStatusReportResultSet1Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (OrderStatusReportInput)state!;
			cmd.Parameters["@FromUtc"].Value = input.FromUtc;
			cmd.Parameters["@ToUtc"].Value = input.ToUtc;
		}
		return new ProcedureExecutionPlan(
			"[sample].[OrderStatusReport]", parameters, resultSets, OutputFactory, AggregateFactory, Binder, enableParameterBinding: false);
	}
}

/// <summary>Convenience extension for executing '[sample].[OrderStatusReport]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class OrderStatusReportExtensions
{
#if XTRAQ_API_MODE_MINIMAL
    public static async Task<OrderStatusReportResult> OrderStatusReportAsync(this IXtraqDbContext db, OrderStatusReportRequest request, CancellationToken cancellationToken = default)
    {
        var bindingProvider = db as IXtraqParameterBindingProvider;
        var input = await OrderStatusReportRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
        return await OrderStatusReportAsync(db, input, cancellationToken).ConfigureAwait(false);
    }
#endif

	public static async Task<OrderStatusReportResult> OrderStatusReportAsync(this IXtraqDbContext db, OrderStatusReportInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await OrderStatusReportProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, OrderStatusReportInput input, Func<OrderStatusReportResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await OrderStatusReportProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, OrderStatusReportInput input, Func<OrderStatusReportResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}
#if XTRAQ_API_MODE_MINIMAL

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, OrderStatusReportRequest request, Func<OrderStatusReportResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await OrderStatusReportRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		await StreamResultResultSet1Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
		return;
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, OrderStatusReportRequest request, Func<OrderStatusReportResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
	}
#endif

}

#if XTRAQ_API_MODE_MINIMAL
/// <summary>Minimal API extension for '[sample].[OrderStatusReport]'.</summary>
public static class OrderStatusReportRouteHandlerBuilderExtensions
{
    public static RouteHandlerBuilder WithOrderStatusReportProcedure(this RouteHandlerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithProcedure<OrderStatusReportRequest, OrderStatusReportResult>(
            static pipeline => pipeline.WithExecutor(
                static async ValueTask<OrderStatusReportResult> (dbContext, request, cancellationToken) =>
                {
                    var bindingProvider = dbContext as IXtraqParameterBindingProvider;
                    var input = await OrderStatusReportRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
                    return await OrderStatusReportExtensions.OrderStatusReportAsync(dbContext, input, cancellationToken).ConfigureAwait(false);
                }));
    }
}
#endif

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class OrderStatusReportProcedure
{
	public const string Name = "[sample].[OrderStatusReport]";
	public static Task<OrderStatusReportResult> ExecuteAsync(DbConnection connection, OrderStatusReportInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<OrderStatusReportResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, OrderStatusReportInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<OrderStatusReportResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, OrderStatusReportInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<OrderStatusReportResult>(interceptorProvider, bindingProvider, connection, OrderStatusReportPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, OrderStatusReportInput input, Func<OrderStatusReportResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, OrderStatusReportInput input, Func<OrderStatusReportResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, OrderStatusReportInput input, Func<OrderStatusReportResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "Status");
            int o1=ReaderUtil.TryGetOrdinal(reader, "Orders");
            int o2=ReaderUtil.TryGetOrdinal(reader, "TotalAmount");
            int o3=ReaderUtil.TryGetOrdinal(reader, "AverageAmount");
            int o4=ReaderUtil.TryGetOrdinal(reader, "LastPlacedAtUtc");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new OrderStatusReportResultSet1Result(o0 < 0 ? string.Empty : (reader.IsDBNull(o0) ? string.Empty : reader.GetString(o0)), o1 < 0 ? null : (reader.IsDBNull(o1) ? null : (long?)reader.GetInt64(o1)), o2 < 0 ? null : (reader.IsDBNull(o2) ? null : (decimal?)reader.GetDecimal(o2)), o3 < 0 ? null : (reader.IsDBNull(o3) ? null : (decimal?)reader.GetDecimal(o3)), o4 < 0 ? null : (reader.IsDBNull(o4) ? null : (DateTime?)reader.GetDateTime(o4)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, OrderStatusReportPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, OrderStatusReportInput input, Func<OrderStatusReportResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, OrderStatusReportInput input, Func<OrderStatusReportResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
