// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.OrderListByUserAsJson</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
public readonly record struct OrderListByUserAsJsonInput(
    int? UserId
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct OrderListByUserAsJsonResultSet1PaymentsResult(
    Guid PaymentId,
    string Gateway,
    decimal Amount,
    DateTime? CapturedAtUtc,
    string? FailureReason
);
public readonly record struct OrderListByUserAsJsonResultSet1Result(
    int OrderId,
    string OrderNumber,
    string Status,
    decimal TotalAmount,
    string Currency,
    DateTime PlacedAtUtc,
    DateTime? RequiredAtUtc,
    System.Collections.Generic.List<OrderListByUserAsJsonResultSet1PaymentsResult> Payments
);

public sealed class OrderListByUserAsJsonResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public OrderListByUserAsJsonResultSet1Result? Result { get; init; } = null;
	/// <summary>
	/// Raw JSON payload captured for result set <c>ResultSet1</c>.
	/// </summary>
	public string? ResultRawJson { get; init; } = null;
}

internal static partial class OrderListByUserAsJsonPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@UserId", System.Data.DbType.Int32, null, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>();
                string? __raw = null;
                var __items = new System.Collections.Generic.List<OrderListByUserAsJsonResultSet1Result>();
                if (await r.ReadAsync(ct).ConfigureAwait(false))
                {
                    if (!r.IsDBNull(0))
                    {
                        __raw = r.GetString(0);
                        try
                        {
                            var __parsed = System.Text.Json.JsonSerializer.Deserialize<OrderListByUserAsJsonResultSet1Result?>(__raw, JsonSupport.Options);
                            if (__parsed is { } __value)
                            {
                                __items.Add(__value);
                            }
                        }
                        catch
                        {
                        }
                    }
                }
                list.Add(JsonResultEnvelope<OrderListByUserAsJsonResultSet1Result>.Create(__items, __raw));
                return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new OrderListByUserAsJsonResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 && rows0.Length > 0 && rows0[0] is JsonResultEnvelope<OrderListByUserAsJsonResultSet1Result> env0 && env0.TryGetFirst(out var value0) ? value0 : (OrderListByUserAsJsonResultSet1Result?)null,
				ResultRawJson = rs.Length > 0 && rs[0] is object[] rows0_raw && rows0_raw.Length > 0 && rows0_raw[0] is JsonResultEnvelope<OrderListByUserAsJsonResultSet1Result> env0_raw ? env0_raw.RawJson : null
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (OrderListByUserAsJsonInput)state!;
			cmd.Parameters["@UserId"].Value = input.UserId;
		}
		return new ProcedureExecutionPlan(
			"[sample].[OrderListByUserAsJson]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[OrderListByUserAsJson]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class OrderListByUserAsJsonExtensions
{
	public static async Task<OrderListByUserAsJsonResult> OrderListByUserAsJsonAsync(this IXtraqDbContext db, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await OrderListByUserAsJsonProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class OrderListByUserAsJsonProcedure
{
	public const string Name = "[sample].[OrderListByUserAsJson]";
	public static Task<OrderListByUserAsJsonResult> ExecuteAsync(DbConnection connection, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<OrderListByUserAsJsonResult>(connection, OrderListByUserAsJsonPlan.Instance, input, cancellationToken);
	}

}
