// <auto-generated/>
// Xtraq Code Generator v1.0.0-alpha. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using System.Data;
using System.Data.Common;

/// <summary>
/// Represents the contract for the stored procedure <c>.</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
public readonly record struct OrderListByUserAsJsonInput(
    int? UserId
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>.ResultSet1</c>.
/// </summary>
public readonly record struct OrderListByUserAsJsonResultSet1PaymentsResult(
    Guid PaymentId,
    string Gateway,
    decimal Amount,
    DateTime? CapturedAtUtc,
    string? FailureReason
);
public readonly record struct OrderListByUserAsJsonResultSet1Result(
    int OrderId,
    string OrderNumber,
    string Status,
    decimal TotalAmount,
    string Currency,
    DateTime PlacedAtUtc,
    DateTime? RequiredAtUtc,
    System.Collections.Generic.List<OrderListByUserAsJsonResultSet1PaymentsResult> Payments
);

public sealed class OrderListByUserAsJsonResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public OrderListByUserAsJsonResultSet1Result? Result { get; init; } = null;
}

internal static partial class OrderListByUserAsJsonPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@UserId", System.Data.DbType.Int32, null, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
    	{
			var list = new System.Collections.Generic.List<object>(); { if (await r.ReadAsync(ct).ConfigureAwait(false) && !r.IsDBNull(0)) { var __raw = r.GetString(0); try { var __single = System.Text.Json.JsonSerializer.Deserialize<OrderListByUserAsJsonResultSet1Result?>(__raw, JsonSupport.Options); if (__single is { } __value) list.Add(__value); } catch { } } } return list;
    	}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new OrderListByUserAsJsonResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 && rows0.Length > 0 && rows0[0] is OrderListByUserAsJsonResultSet1Result first0 ? first0 : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 && list0.Count > 0 && list0[0] is OrderListByUserAsJsonResultSet1Result listFirst0 ? listFirst0 : (OrderListByUserAsJsonResultSet1Result?)null)
			};
		};
		void Binder(DbCommand cmd, object? state)
		{
			var input = (OrderListByUserAsJsonInput)state!;
			cmd.Parameters["@UserId"].Value = input.UserId;
		}
		return new ProcedureExecutionPlan(
			"[sample].[OrderListByUserAsJson]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[OrderListByUserAsJson]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class OrderListByUserAsJsonExtensions
{
	public static async Task<OrderListByUserAsJsonResult> OrderListByUserAsJsonAsync(this IXtraqDbContext db, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await OrderListByUserAsJsonProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class OrderListByUserAsJsonProcedure
{
	public const string Name = "[sample].[OrderListByUserAsJson]";
	public static Task<OrderListByUserAsJsonResult> ExecuteAsync(DbConnection connection, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<OrderListByUserAsJsonResult>(connection, OrderListByUserAsJsonPlan.Instance, input, cancellationToken);
	}
}
