// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Represents the contract for the stored procedure <c>.</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
public readonly record struct OrderStatusReportInput(
    DateTime? FromUtc,
    DateTime? ToUtc
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>.ResultSet1</c>.
/// </summary>
public readonly record struct OrderStatusReportResultSet1Result(
    string Status,
    long? Orders,
    decimal? TotalAmount,
    decimal? AverageAmount,
    DateTime? LastPlacedAtUtc
);

public sealed class OrderStatusReportResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<OrderStatusReportResultSet1Result> Result { get; init; } = Array.Empty<OrderStatusReportResultSet1Result>();
}

internal static partial class OrderStatusReportPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@FromUtc", System.Data.DbType.DateTime2, null, false, true),
            new("@ToUtc", System.Data.DbType.DateTime2, null, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "Status"); int o1=ReaderUtil.TryGetOrdinal(r, "Orders"); int o2=ReaderUtil.TryGetOrdinal(r, "TotalAmount"); int o3=ReaderUtil.TryGetOrdinal(r, "AverageAmount"); int o4=ReaderUtil.TryGetOrdinal(r, "LastPlacedAtUtc"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new OrderStatusReportResultSet1Result(o0 < 0 ? string.Empty : (r.IsDBNull(o0) ? string.Empty : r.GetString(o0)), o1 < 0 ? null : (r.IsDBNull(o1) ? null : (long?)r.GetInt64(o1)), o2 < 0 ? null : (r.IsDBNull(o2) ? null : (decimal?)r.GetDecimal(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : (decimal?)r.GetDecimal(o3)), o4 < 0 ? null : (r.IsDBNull(o4) ? null : (DateTime?)r.GetDateTime(o4)))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new OrderStatusReportResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (OrderStatusReportResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (OrderStatusReportResultSet1Result)o).ToList() : Array.Empty<OrderStatusReportResultSet1Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (OrderStatusReportInput)state!;
			cmd.Parameters["@FromUtc"].Value = input.FromUtc;
			cmd.Parameters["@ToUtc"].Value = input.ToUtc;
		}
		return new ProcedureExecutionPlan(
			"[sample].[OrderStatusReport]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[OrderStatusReport]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class OrderStatusReportExtensions
{
	public static async Task<OrderStatusReportResult> OrderStatusReportAsync(this IXtraqDbContext db, OrderStatusReportInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await OrderStatusReportProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, Func<OrderStatusReportResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await Procedure.StreamResultResultSet1Async(connection, onRowAsync, cancellationToken).ConfigureAwait(false);
		
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, Func<OrderStatusReportResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, (row, ct) => onRowAsync(row), cancellationToken);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class OrderStatusReportProcedure
{
	public const string Name = "[sample].[OrderStatusReport]";
	public static Task<OrderStatusReportResult> ExecuteAsync(DbConnection connection, OrderStatusReportInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<OrderStatusReportResult>(connection, OrderStatusReportPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static async Task StreamResultResultSet1Async(DbConnection connection, Func<OrderStatusReportResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(r, "Status");
            int o1=ReaderUtil.TryGetOrdinal(r, "Orders");
            int o2=ReaderUtil.TryGetOrdinal(r, "TotalAmount");
            int o3=ReaderUtil.TryGetOrdinal(r, "AverageAmount");
            int o4=ReaderUtil.TryGetOrdinal(r, "LastPlacedAtUtc");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new OrderStatusReportResultSet1Result(o0 < 0 ? string.Empty : (r.IsDBNull(o0) ? string.Empty : r.GetString(o0)), o1 < 0 ? null : (r.IsDBNull(o1) ? null : (long?)r.GetInt64(o1)), o2 < 0 ? null : (r.IsDBNull(o2) ? null : (decimal?)r.GetDecimal(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : (decimal?)r.GetDecimal(o3)), o4 < 0 ? null : (r.IsDBNull(o4) ? null : (DateTime?)r.GetDateTime(o4)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(connection, .Instance, 0, StreamCoreAsync, null, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, Func<OrderStatusReportResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(connection, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
