// <auto-generated/>
// Xtraq Code Generator v1.0.0-alpha.6. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Represents the contract for the stored procedure <c>.</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
public readonly record struct SyncUserContactsInput(
    IReadOnlyList<UserContactTableType>? Contacts
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>.ResultSet1</c>.
/// </summary>
public readonly record struct SyncUserContactsResultSet1Result(
    string MergeAction,
    int ContactId,
    int UserId,
    string Email,
    string DisplayName,
    bool Preferred,
    DateTime? LastInteractionUtc,
    DateTime? UpdatedAtUtc
);

public sealed class SyncUserContactsResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<SyncUserContactsResultSet1Result> Result { get; init; } = Array.Empty<SyncUserContactsResultSet1Result>();
}

internal static partial class SyncUserContactsPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Contacts", System.Data.DbType.Object, null, false, false),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "MergeAction"); int o1=ReaderUtil.TryGetOrdinal(r, "ContactId"); int o2=ReaderUtil.TryGetOrdinal(r, "UserId"); int o3=ReaderUtil.TryGetOrdinal(r, "Email"); int o4=ReaderUtil.TryGetOrdinal(r, "DisplayName"); int o5=ReaderUtil.TryGetOrdinal(r, "Preferred"); int o6=ReaderUtil.TryGetOrdinal(r, "LastInteractionUtc"); int o7=ReaderUtil.TryGetOrdinal(r, "UpdatedAtUtc"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new SyncUserContactsResultSet1Result(o0 < 0 ? string.Empty : (r.IsDBNull(o0) ? string.Empty : r.GetString(o0)), o1 < 0 ? default(int) : r.GetInt32(o1), o2 < 0 ? default(int) : r.GetInt32(o2), o3 < 0 ? string.Empty : (r.IsDBNull(o3) ? string.Empty : r.GetString(o3)), o4 < 0 ? string.Empty : (r.IsDBNull(o4) ? string.Empty : r.GetString(o4)), o5 < 0 ? default(bool) : r.GetBoolean(o5), o6 < 0 ? null : (r.IsDBNull(o6) ? null : (DateTime?)r.GetDateTime(o6)), o7 < 0 ? null : (r.IsDBNull(o7) ? null : (DateTime?)r.GetDateTime(o7)))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new SyncUserContactsResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (SyncUserContactsResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (SyncUserContactsResultSet1Result)o).ToList() : Array.Empty<SyncUserContactsResultSet1Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (SyncUserContactsInput)state!;
			{ var prm = cmd.Parameters["@Contacts"]; prm.Value = TvpHelper.BuildRecords(input.Contacts) ?? (object)DBNull.Value; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) sp.SqlDbType = System.Data.SqlDbType.Structured; }
		}
		return new ProcedureExecutionPlan(
			"[sample].[SyncUserContacts]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[SyncUserContacts]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class SyncUserContactsExtensions
{
	public static async Task<SyncUserContactsResult> SyncUserContactsAsync(this IXtraqDbContext db, SyncUserContactsInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await SyncUserContactsProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class SyncUserContactsProcedure
{
	public const string Name = "[sample].[SyncUserContacts]";
	public static Task<SyncUserContactsResult> ExecuteAsync(DbConnection connection, SyncUserContactsInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<SyncUserContactsResult>(connection, SyncUserContactsPlan.Instance, input, cancellationToken);
	}
}
