// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.SyncUserContacts</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class SyncUserContactsRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<UserContactTableTypeRequest> Contacts { get; init; } = default!;
}

public readonly record struct SyncUserContactsInput(
    IReadOnlyList<UserContactTableType> Contacts
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct SyncUserContactsResultSet1Result(
    string MergeAction,
    int ContactId,
    int UserId,
    string Email,
    string DisplayName,
    bool Preferred,
    DateTime? LastInteractionUtc,
    DateTime? UpdatedAtUtc
);

public sealed class SyncUserContactsResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<SyncUserContactsResultSet1Result> Result { get; init; } = Array.Empty<SyncUserContactsResultSet1Result>();
}
internal static class SyncUserContactsRequestMapper
{
    public static async ValueTask<SyncUserContactsInput> ToInputAsync(SyncUserContactsRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new SyncUserContactsRequest();
        IReadOnlyList<UserContactTableType>? Contacts = UserContactTableTypeRequest.ToTableTypes(request.Contacts);
		if (!HasValue(Contacts))
		{
			throw new InvalidOperationException("Parameter @Contacts must be supplied by the request or a configured binding.");
		}

        return new SyncUserContactsInput(
            Contacts!
        );
    }

    public static ValueTask<SyncUserContactsInput> ToInputAsync(SyncUserContactsRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class SyncUserContactsPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Contacts", System.Data.DbType.Object, null, false, false, "sample.UserContactTableType"),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "MergeAction"); int o1=ReaderUtil.TryGetOrdinal(r, "ContactId"); int o2=ReaderUtil.TryGetOrdinal(r, "UserId"); int o3=ReaderUtil.TryGetOrdinal(r, "Email"); int o4=ReaderUtil.TryGetOrdinal(r, "DisplayName"); int o5=ReaderUtil.TryGetOrdinal(r, "Preferred"); int o6=ReaderUtil.TryGetOrdinal(r, "LastInteractionUtc"); int o7=ReaderUtil.TryGetOrdinal(r, "UpdatedAtUtc"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new SyncUserContactsResultSet1Result(o0 < 0 ? string.Empty : (r.IsDBNull(o0) ? string.Empty : r.GetString(o0)), o1 < 0 ? default(int) : r.GetInt32(o1), o2 < 0 ? default(int) : r.GetInt32(o2), o3 < 0 ? string.Empty : (r.IsDBNull(o3) ? string.Empty : r.GetString(o3)), o4 < 0 ? string.Empty : (r.IsDBNull(o4) ? string.Empty : r.GetString(o4)), o5 < 0 ? default(bool) : r.GetBoolean(o5), o6 < 0 ? null : (r.IsDBNull(o6) ? null : (DateTime?)r.GetDateTime(o6)), o7 < 0 ? null : (r.IsDBNull(o7) ? null : (DateTime?)r.GetDateTime(o7)))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new SyncUserContactsResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (SyncUserContactsResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (SyncUserContactsResultSet1Result)o).ToList() : Array.Empty<SyncUserContactsResultSet1Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (SyncUserContactsInput)state!;
			{ var prm = cmd.Parameters["@Contacts"]; var source = input.Contacts; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "sample.UserContactTableType"; } }
		}
		return new ProcedureExecutionPlan(
			"[sample].[SyncUserContacts]", parameters, resultSets, OutputFactory, AggregateFactory, Binder, enableParameterBinding: false);
	}
}

/// <summary>Convenience extension for executing '[sample].[SyncUserContacts]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class SyncUserContactsExtensions
{
	public static async Task<SyncUserContactsResult> SyncUserContactsAsync(this IXtraqDbContext db, SyncUserContactsRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await SyncUserContactsRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await SyncUserContactsAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<SyncUserContactsResult> SyncUserContactsAsync(this IXtraqDbContext db, SyncUserContactsInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await SyncUserContactsProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, SyncUserContactsInput input, Func<SyncUserContactsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await SyncUserContactsProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, SyncUserContactsInput input, Func<SyncUserContactsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, SyncUserContactsRequest request, Func<SyncUserContactsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await SyncUserContactsRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		await StreamResultResultSet1Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
		return;
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, SyncUserContactsRequest request, Func<SyncUserContactsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class SyncUserContactsProcedure
{
	public const string Name = "[sample].[SyncUserContacts]";
	public static Task<SyncUserContactsResult> ExecuteAsync(DbConnection connection, SyncUserContactsInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<SyncUserContactsResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, SyncUserContactsInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<SyncUserContactsResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, SyncUserContactsInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<SyncUserContactsResult>(interceptorProvider, bindingProvider, connection, SyncUserContactsPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, SyncUserContactsInput input, Func<SyncUserContactsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, SyncUserContactsInput input, Func<SyncUserContactsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, SyncUserContactsInput input, Func<SyncUserContactsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "MergeAction");
            int o1=ReaderUtil.TryGetOrdinal(reader, "ContactId");
            int o2=ReaderUtil.TryGetOrdinal(reader, "UserId");
            int o3=ReaderUtil.TryGetOrdinal(reader, "Email");
            int o4=ReaderUtil.TryGetOrdinal(reader, "DisplayName");
            int o5=ReaderUtil.TryGetOrdinal(reader, "Preferred");
            int o6=ReaderUtil.TryGetOrdinal(reader, "LastInteractionUtc");
            int o7=ReaderUtil.TryGetOrdinal(reader, "UpdatedAtUtc");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new SyncUserContactsResultSet1Result(o0 < 0 ? string.Empty : (reader.IsDBNull(o0) ? string.Empty : reader.GetString(o0)), o1 < 0 ? default(int) : reader.GetInt32(o1), o2 < 0 ? default(int) : reader.GetInt32(o2), o3 < 0 ? string.Empty : (reader.IsDBNull(o3) ? string.Empty : reader.GetString(o3)), o4 < 0 ? string.Empty : (reader.IsDBNull(o4) ? string.Empty : reader.GetString(o4)), o5 < 0 ? default(bool) : reader.GetBoolean(o5), o6 < 0 ? null : (reader.IsDBNull(o6) ? null : (DateTime?)reader.GetDateTime(o6)), o7 < 0 ? null : (reader.IsDBNull(o7) ? null : (DateTime?)reader.GetDateTime(o7)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, SyncUserContactsPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, SyncUserContactsInput input, Func<SyncUserContactsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, SyncUserContactsInput input, Func<SyncUserContactsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
