// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
#if XTRAQ_API_MODE_MINIMAL
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
#endif

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.UnionOrderStatuses</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct UnionOrderStatusesResultSet1Result(
    int Quantity,
    string Day
);

public sealed class UnionOrderStatusesResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UnionOrderStatusesResultSet1Result> Result { get; init; } = Array.Empty<UnionOrderStatusesResultSet1Result>();
	/// <summary>
	/// Raw JSON payload captured for result set <c>ResultSet1</c>.
	/// </summary>
	public string? ResultRawJson { get; init; } = null;
}

#if XTRAQ_API_MODE_MINIMAL
#endif

internal static partial class UnionOrderStatusesPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = Array.Empty<ProcedureParameter>();

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>();
                var __sb = new System.Text.StringBuilder();
                while (await r.ReadAsync(ct).ConfigureAwait(false))
                {
                    if (!r.IsDBNull(0))
                    {
                        __sb.Append(r.GetString(0));
                    }
                }
                var __raw = __sb.Length > 0 ? __sb.ToString() : null;
                var __items = new System.Collections.Generic.List<UnionOrderStatusesResultSet1Result>();
                if (__raw != null)
                {
                    try
                    {
                        var __parsed = System.Text.Json.JsonSerializer.Deserialize<System.Collections.Generic.List<UnionOrderStatusesResultSet1Result?>>(__raw, JsonSupport.Options);
                        if (__parsed is not null)
                        {
                            foreach (var __entry in __parsed)
                            {
                                if (__entry is { } __value)
                                {
                                    __items.Add(__value);
                                }
                            }
                        }
                    }
                    catch
                    {
                    }
                }
                list.Add(JsonResultEnvelope<UnionOrderStatusesResultSet1Result>.Create(__items, __raw));
                return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UnionOrderStatusesResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 && rows0.Length > 0 && rows0[0] is JsonResultEnvelope<UnionOrderStatusesResultSet1Result> env0 ? env0.Items : System.Array.Empty<UnionOrderStatusesResultSet1Result>(),
				ResultRawJson = rs.Length > 0 && rs[0] is object[] rows0_raw && rows0_raw.Length > 0 && rows0_raw[0] is JsonResultEnvelope<UnionOrderStatusesResultSet1Result> env0_raw ? env0_raw.RawJson : null
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
		}
		return new ProcedureExecutionPlan(
			"[sample].[UnionOrderStatuses]", parameters, resultSets, OutputFactory, AggregateFactory, Binder, enableParameterBinding: false);
	}
}

/// <summary>Convenience extension for executing '[sample].[UnionOrderStatuses]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UnionOrderStatusesExtensions
{
#if XTRAQ_API_MODE_MINIMAL
#endif

	public static async Task<UnionOrderStatusesResult> UnionOrderStatusesAsync(this IXtraqDbContext db, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UnionOrderStatusesProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, cancellationToken).ConfigureAwait(false);
	}

}

#if XTRAQ_API_MODE_MINIMAL
/// <summary>Minimal API extension for '[sample].[UnionOrderStatuses]'.</summary>
public static class UnionOrderStatusesRouteHandlerBuilderExtensions
{
    public static RouteHandlerBuilder WithUnionOrderStatusesProcedure(this RouteHandlerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithProcedure<object?, UnionOrderStatusesResult>(
            static pipeline => pipeline.WithExecutor(
                static async ValueTask<UnionOrderStatusesResult> (dbContext, _, cancellationToken) =>
                {
                    return await UnionOrderStatusesExtensions.UnionOrderStatusesAsync(dbContext, cancellationToken).ConfigureAwait(false);
                }));
    }
}
#endif

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UnionOrderStatusesProcedure
{
	public const string Name = "[sample].[UnionOrderStatuses]";
	public static Task<UnionOrderStatusesResult> ExecuteAsync(DbConnection connection, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, cancellationToken);

	public static Task<UnionOrderStatusesResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, cancellationToken);

	public static Task<UnionOrderStatusesResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UnionOrderStatusesResult>(interceptorProvider, bindingProvider, connection, UnionOrderStatusesPlan.Instance, null, cancellationToken);
	}

}
