// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
#if NET8_0_OR_GREATER && XTRAQ_MINIMAL_API
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
#endif

/// <summary>
/// Represents the contract for the stored procedure <c>sample.UserOrderHierarchyJson</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Represents the result set <c>Users</c> emitted by <c>sample.Users</c>.
/// </summary>
public readonly record struct UserOrderHierarchyJsonUsersOrdersPaymentsResult(
    Guid PaymentId,
    string Gateway,
    decimal Amount,
    DateTime? CapturedAtUtc
);

public readonly record struct UserOrderHierarchyJsonUsersOrdersResult(
    int OrderId,
    string OrderNumber,
    string Status,
    decimal TotalAmount,
    string Currency,
    DateTime PlacedAtUtc,
    System.Collections.Generic.List<UserOrderHierarchyJsonUsersOrdersPaymentsResult> Payments
);
public readonly record struct UserOrderHierarchyJsonUsersResult(
    int UserId,
    string? Alias,
    string DisplayName,
    string? Email,
    System.Collections.Generic.List<UserOrderHierarchyJsonUsersOrdersResult> Orders
);

public sealed class UserOrderHierarchyJsonResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>Users</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserOrderHierarchyJsonUsersResult> Users { get; init; } = Array.Empty<UserOrderHierarchyJsonUsersResult>();
	/// <summary>
	/// Raw JSON payload captured for result set <c>Users</c>.
	/// </summary>
	public string? UsersRawJson { get; init; } = null;
}

internal static partial class UserOrderHierarchyJsonPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = Array.Empty<ProcedureParameter>();

		var resultSets = new ResultSetMapping[]
		{
            new("Users", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>();
                var __sb = new System.Text.StringBuilder();
                while (await r.ReadAsync(ct).ConfigureAwait(false))
                {
                    if (!r.IsDBNull(0))
                    {
                        __sb.Append(r.GetString(0));
                    }
                }
                var __raw = __sb.Length > 0 ? __sb.ToString() : null;
                if (__raw != null)
                {
                    try
                    {
                        using var __doc = System.Text.Json.JsonDocument.Parse(__raw);
                        if (__doc.RootElement.ValueKind == System.Text.Json.JsonValueKind.Object && __doc.RootElement.TryGetProperty("Users", out var __root))
                        {
                            __raw = __root.GetRawText();
                        }
                    }
                    catch { }
                }
                var __items = new System.Collections.Generic.List<UserOrderHierarchyJsonUsersResult>();
                if (__raw != null)
                {
                    try
                    {
                        var __parsed = System.Text.Json.JsonSerializer.Deserialize<System.Collections.Generic.List<UserOrderHierarchyJsonUsersResult?>>(__raw, JsonSupport.Options);
                        if (__parsed is not null)
                        {
                            foreach (var __entry in __parsed)
                            {
                                if (__entry is { } __value)
                                {
                                    __items.Add(__value);
                                }
                            }
                        }
                    }
                    catch
                    {
                    }
                }
                list.Add(JsonResultEnvelope<UserOrderHierarchyJsonUsersResult>.Create(__items, __raw));
                return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserOrderHierarchyJsonResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Users
				Users = rs.Length > 0 && rs[0] is object[] rows0 && rows0.Length > 0 && rows0[0] is JsonResultEnvelope<UserOrderHierarchyJsonUsersResult> env0 ? env0.Items : System.Array.Empty<UserOrderHierarchyJsonUsersResult>(),
				UsersRawJson = rs.Length > 0 && rs[0] is object[] rows0_raw && rows0_raw.Length > 0 && rows0_raw[0] is JsonResultEnvelope<UserOrderHierarchyJsonUsersResult> env0_raw ? env0_raw.RawJson : null
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
		}
		return new ProcedureExecutionPlan(
			"[sample].[UserOrderHierarchyJson]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[UserOrderHierarchyJson]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UserOrderHierarchyJsonExtensions
{
	public static async Task<UserOrderHierarchyJsonResult> UserOrderHierarchyJsonAsync(this IXtraqDbContext db, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserOrderHierarchyJsonProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, conn, cancellationToken).ConfigureAwait(false);
	}

}

#if NET8_0_OR_GREATER && XTRAQ_MINIMAL_API
/// <summary>Minimal API extension for '[sample].[UserOrderHierarchyJson]'.</summary>
public static class UserOrderHierarchyJsonRouteHandlerBuilderExtensions
{
    public static RouteHandlerBuilder WithUserOrderHierarchyJsonProcedure(this RouteHandlerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithProcedure<object?, UserOrderHierarchyJsonResult>(
            static pipeline => pipeline.WithExecutor(
                static (dbContext, _, cancellationToken) => new ValueTask<UserOrderHierarchyJsonResult>(
                    UserOrderHierarchyJsonExtensions.UserOrderHierarchyJsonAsync(dbContext, cancellationToken))));
    }
}
#endif

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserOrderHierarchyJsonProcedure
{
	public const string Name = "[sample].[UserOrderHierarchyJson]";
	public static Task<UserOrderHierarchyJsonResult> ExecuteAsync(DbConnection connection, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, connection, cancellationToken);

	public static Task<UserOrderHierarchyJsonResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserOrderHierarchyJsonResult>(interceptorProvider, connection, UserOrderHierarchyJsonPlan.Instance, null, cancellationToken);
	}

}
