// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.UserDetailsWithOrders</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
public readonly record struct UserDetailsWithOrdersInput(
    int? UserId
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct UserDetailsWithOrdersResultSet1Result(
    int UserId,
    string? Alias,
    string DisplayName,
    string? Email,
    bool IsActive,
    string PreferredLocale,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc,
    string? Metadata
);

/// <summary>
/// Represents the result set <c>ResultSet2</c> emitted by <c>sample.ResultSet2</c>.
/// </summary>
public readonly record struct UserDetailsWithOrdersResultSet2Result(
    int OrderId,
    string OrderNumber,
    string Status,
    decimal TotalAmount,
    string Currency,
    DateTime PlacedAtUtc,
    DateTime? RequiredAtUtc,
    int HasOutstandingBalance
);

public sealed class UserDetailsWithOrdersResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserDetailsWithOrdersResultSet1Result> Result { get; init; } = Array.Empty<UserDetailsWithOrdersResultSet1Result>();
	/// <summary>
	/// Result set <c>ResultSet2</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserDetailsWithOrdersResultSet2Result> Result1 { get; init; } = Array.Empty<UserDetailsWithOrdersResultSet2Result>();
}

internal static partial class UserDetailsWithOrdersPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@UserId", System.Data.DbType.Int32, null, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "UserId"); int o1=ReaderUtil.TryGetOrdinal(r, "Alias"); int o2=ReaderUtil.TryGetOrdinal(r, "DisplayName"); int o3=ReaderUtil.TryGetOrdinal(r, "Email"); int o4=ReaderUtil.TryGetOrdinal(r, "IsActive"); int o5=ReaderUtil.TryGetOrdinal(r, "PreferredLocale"); int o6=ReaderUtil.TryGetOrdinal(r, "CreatedAtUtc"); int o7=ReaderUtil.TryGetOrdinal(r, "UpdatedAtUtc"); int o8=ReaderUtil.TryGetOrdinal(r, "Metadata"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserDetailsWithOrdersResultSet1Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? null : (r.IsDBNull(o1) ? null : r.GetString(o1)), o2 < 0 ? string.Empty : (r.IsDBNull(o2) ? string.Empty : r.GetString(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : r.GetString(o3)), o4 < 0 ? default(bool) : r.GetBoolean(o4), o5 < 0 ? string.Empty : (r.IsDBNull(o5) ? string.Empty : r.GetString(o5)), o6 < 0 ? default(DateTime) : r.GetDateTime(o6), o7 < 0 ? null : (r.IsDBNull(o7) ? null : (DateTime?)r.GetDateTime(o7)), o8 < 0 ? null : (r.IsDBNull(o8) ? null : r.GetString(o8)))); } return list;
			}),

            new("ResultSet2", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "OrderId"); int o1=ReaderUtil.TryGetOrdinal(r, "OrderNumber"); int o2=ReaderUtil.TryGetOrdinal(r, "Status"); int o3=ReaderUtil.TryGetOrdinal(r, "TotalAmount"); int o4=ReaderUtil.TryGetOrdinal(r, "Currency"); int o5=ReaderUtil.TryGetOrdinal(r, "PlacedAtUtc"); int o6=ReaderUtil.TryGetOrdinal(r, "RequiredAtUtc"); int o7=ReaderUtil.TryGetOrdinal(r, "HasOutstandingBalance"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserDetailsWithOrdersResultSet2Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? string.Empty : (r.IsDBNull(o1) ? string.Empty : r.GetString(o1)), o2 < 0 ? string.Empty : (r.IsDBNull(o2) ? string.Empty : r.GetString(o2)), o3 < 0 ? default(decimal) : r.GetDecimal(o3), o4 < 0 ? string.Empty : (r.IsDBNull(o4) ? string.Empty : r.GetString(o4)), o5 < 0 ? default(DateTime) : r.GetDateTime(o5), o6 < 0 ? null : (r.IsDBNull(o6) ? null : (DateTime?)r.GetDateTime(o6)), o7 < 0 ? default(int) : r.GetInt32(o7))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserDetailsWithOrdersResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (UserDetailsWithOrdersResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (UserDetailsWithOrdersResultSet1Result)o).ToList() : Array.Empty<UserDetailsWithOrdersResultSet1Result>()),
				// ResultSet 1 -> Result1
				Result1 = rs.Length > 1 && rs[1] is object[] rows1 ? Array.ConvertAll(rows1, o => (UserDetailsWithOrdersResultSet2Result)o).ToList() : (rs.Length > 1 && rs[1] is System.Collections.Generic.List<object> list1 ? Array.ConvertAll(list1.ToArray(), o => (UserDetailsWithOrdersResultSet2Result)o).ToList() : Array.Empty<UserDetailsWithOrdersResultSet2Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (UserDetailsWithOrdersInput)state!;
			cmd.Parameters["@UserId"].Value = (object?)input.UserId ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[sample].[UserDetailsWithOrders]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[UserDetailsWithOrders]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UserDetailsWithOrdersExtensions
{
	public static async Task<UserDetailsWithOrdersResult> UserDetailsWithOrdersAsync(this IXtraqDbContext db, UserDetailsWithOrdersInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserDetailsWithOrdersProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await UserDetailsWithOrdersProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet2</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet2Async(this IXtraqDbContext db, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet2Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await UserDetailsWithOrdersProcedure.StreamResultResultSet2Async(db as IXtraqProcedureInterceptorProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet2Async(this IXtraqDbContext db, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet2Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet2Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserDetailsWithOrdersProcedure
{
	public const string Name = "[sample].[UserDetailsWithOrders]";
	public static Task<UserDetailsWithOrdersResult> ExecuteAsync(DbConnection connection, UserDetailsWithOrdersInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, connection, input, cancellationToken);

	public static Task<UserDetailsWithOrdersResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserDetailsWithOrdersInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserDetailsWithOrdersResult>(interceptorProvider, connection, UserDetailsWithOrdersPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "UserId");
            int o1=ReaderUtil.TryGetOrdinal(reader, "Alias");
            int o2=ReaderUtil.TryGetOrdinal(reader, "DisplayName");
            int o3=ReaderUtil.TryGetOrdinal(reader, "Email");
            int o4=ReaderUtil.TryGetOrdinal(reader, "IsActive");
            int o5=ReaderUtil.TryGetOrdinal(reader, "PreferredLocale");
            int o6=ReaderUtil.TryGetOrdinal(reader, "CreatedAtUtc");
            int o7=ReaderUtil.TryGetOrdinal(reader, "UpdatedAtUtc");
            int o8=ReaderUtil.TryGetOrdinal(reader, "Metadata");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new UserDetailsWithOrdersResultSet1Result(o0 < 0 ? default(int) : reader.GetInt32(o0), o1 < 0 ? null : (reader.IsDBNull(o1) ? null : reader.GetString(o1)), o2 < 0 ? string.Empty : (reader.IsDBNull(o2) ? string.Empty : reader.GetString(o2)), o3 < 0 ? null : (reader.IsDBNull(o3) ? null : reader.GetString(o3)), o4 < 0 ? default(bool) : reader.GetBoolean(o4), o5 < 0 ? string.Empty : (reader.IsDBNull(o5) ? string.Empty : reader.GetString(o5)), o6 < 0 ? default(DateTime) : reader.GetDateTime(o6), o7 < 0 ? null : (reader.IsDBNull(o7) ? null : (DateTime?)reader.GetDateTime(o7)), o8 < 0 ? null : (reader.IsDBNull(o8) ? null : reader.GetString(o8)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, connection, UserDetailsWithOrdersPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet2</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet2Async(DbConnection connection, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet2Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet2Async(null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet2Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet2Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "OrderId");
            int o1=ReaderUtil.TryGetOrdinal(reader, "OrderNumber");
            int o2=ReaderUtil.TryGetOrdinal(reader, "Status");
            int o3=ReaderUtil.TryGetOrdinal(reader, "TotalAmount");
            int o4=ReaderUtil.TryGetOrdinal(reader, "Currency");
            int o5=ReaderUtil.TryGetOrdinal(reader, "PlacedAtUtc");
            int o6=ReaderUtil.TryGetOrdinal(reader, "RequiredAtUtc");
            int o7=ReaderUtil.TryGetOrdinal(reader, "HasOutstandingBalance");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new UserDetailsWithOrdersResultSet2Result(o0 < 0 ? default(int) : reader.GetInt32(o0), o1 < 0 ? string.Empty : (reader.IsDBNull(o1) ? string.Empty : reader.GetString(o1)), o2 < 0 ? string.Empty : (reader.IsDBNull(o2) ? string.Empty : reader.GetString(o2)), o3 < 0 ? default(decimal) : reader.GetDecimal(o3), o4 < 0 ? string.Empty : (reader.IsDBNull(o4) ? string.Empty : reader.GetString(o4)), o5 < 0 ? default(DateTime) : reader.GetDateTime(o5), o6 < 0 ? null : (reader.IsDBNull(o6) ? null : (DateTime?)reader.GetDateTime(o6)), o7 < 0 ? default(int) : reader.GetInt32(o7));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, connection, UserDetailsWithOrdersPlan.Instance, 1, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet2Async(DbConnection connection, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet2Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet2Async(null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet2Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserDetailsWithOrdersInput input, Func<UserDetailsWithOrdersResultSet2Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet2Async(interceptorProvider, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
