// <auto-generated/>
// Xtraq Code Generator v1.0.0-alpha.6. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Represents the contract for the stored procedure <c>.</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>.ResultSet1</c>.
/// </summary>
public readonly record struct UserOrderHierarchyJsonResultSet1OrdersPaymentsResult(
    Guid PaymentId,
    string Gateway,
    decimal Amount,
    DateTime? CapturedAtUtc
);

public readonly record struct UserOrderHierarchyJsonResultSet1OrdersResult(
    int OrderId,
    string OrderNumber,
    string Status,
    decimal TotalAmount,
    string Currency,
    DateTime PlacedAtUtc,
    System.Collections.Generic.List<UserOrderHierarchyJsonResultSet1OrdersPaymentsResult> Payments
);
public readonly record struct UserOrderHierarchyJsonResultSet1Result(
    int UserId,
    string? Alias,
    string DisplayName,
    string? Email,
    System.Collections.Generic.List<UserOrderHierarchyJsonResultSet1OrdersResult> Orders
);

public sealed class UserOrderHierarchyJsonResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserOrderHierarchyJsonResultSet1Result> Result { get; init; } = Array.Empty<UserOrderHierarchyJsonResultSet1Result>();
	/// <summary>
	/// Raw JSON payload captured for result set <c>ResultSet1</c>.
	/// </summary>
	public string? ResultRawJson { get; init; } = null;
}

internal static partial class UserOrderHierarchyJsonPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = Array.Empty<ProcedureParameter>();

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>();
                string? __raw = null;
                var __items = new System.Collections.Generic.List<UserOrderHierarchyJsonResultSet1Result>();
                if (await r.ReadAsync(ct).ConfigureAwait(false))
                {
                    if (!r.IsDBNull(0))
                    {
                        __raw = r.GetString(0);
                        try
                        {
                            var __parsed = System.Text.Json.JsonSerializer.Deserialize<System.Collections.Generic.List<UserOrderHierarchyJsonResultSet1Result?>>(__raw, JsonSupport.Options);
                            if (__parsed is not null)
                            {
                                foreach (var __entry in __parsed)
                                {
                                    if (__entry is { } __value)
                                    {
                                        __items.Add(__value);
                                    }
                                }
                            }
                        }
                        catch
                        {
                        }
                    }
                }
                list.Add(JsonResultEnvelope<UserOrderHierarchyJsonResultSet1Result>.Create(__items, __raw));
                return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserOrderHierarchyJsonResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 && rows0.Length > 0 && rows0[0] is JsonResultEnvelope<UserOrderHierarchyJsonResultSet1Result> env0 ? env0.Items : System.Array.Empty<UserOrderHierarchyJsonResultSet1Result>(),
				ResultRawJson = rs.Length > 0 && rs[0] is object[] rows0_raw && rows0_raw.Length > 0 && rows0_raw[0] is JsonResultEnvelope<UserOrderHierarchyJsonResultSet1Result> env0_raw ? env0_raw.RawJson : null
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
		}
		return new ProcedureExecutionPlan(
			"[sample].[UserOrderHierarchyJson]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[UserOrderHierarchyJson]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UserOrderHierarchyJsonExtensions
{
	public static async Task<UserOrderHierarchyJsonResult> UserOrderHierarchyJsonAsync(this IXtraqDbContext db, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserOrderHierarchyJsonProcedure.ExecuteAsync(conn, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserOrderHierarchyJsonProcedure
{
	public const string Name = "[sample].[UserOrderHierarchyJson]";
	public static Task<UserOrderHierarchyJsonResult> ExecuteAsync(DbConnection connection, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserOrderHierarchyJsonResult>(connection, UserOrderHierarchyJsonPlan.Instance, null, cancellationToken);
	}
}
