// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.UserPreferredContactApply</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for Minimal API / external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class UserPreferredContactApplyRequest
{
    public int? UserId { get; init; }
    public bool? OnlyPreferred { get; init; }
}

public readonly record struct UserPreferredContactApplyInput(
    int? UserId,
    bool? OnlyPreferred
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct UserPreferredContactApplyResultSet1Result(
    int UserId,
    string DisplayName,
    string? Email,
    bool IsActive,
    string? PreferredEmail,
    string? PreferredDisplayName,
    string? PreferredSource,
    DateTime? PreferredLastInteractionUtc,
    string PreferredRank
);

/// <summary>
/// Represents the result set <c>ResultSet2</c> emitted by <c>sample.ResultSet2</c>.
/// </summary>
public readonly record struct UserPreferredContactApplyResultSet2PreferredContactJsonResult(
    string Email,
    string DisplayName,
    string Source,
    bool Preferred,
    DateTime? LastInteractionUtc
);
public readonly record struct UserPreferredContactApplyResultSet2Result(
    int UserId,
    UserPreferredContactApplyResultSet2PreferredContactJsonResult? PreferredContactJson
);

public sealed class UserPreferredContactApplyResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserPreferredContactApplyResultSet1Result> Result { get; init; } = Array.Empty<UserPreferredContactApplyResultSet1Result>();
	/// <summary>
	/// Result set <c>ResultSet2</c> projected as a strongly typed sequence.
	/// </summary>
	public UserPreferredContactApplyResultSet2Result? Result1 { get; init; } = null;
	/// <summary>
	/// Raw JSON payload captured for result set <c>ResultSet2</c>.
	/// </summary>
	public string? Result1RawJson { get; init; } = null;
}

internal static class UserPreferredContactApplyRequestMapper
{
    public static async ValueTask<UserPreferredContactApplyInput> ToInputAsync(UserPreferredContactApplyRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new UserPreferredContactApplyRequest();
        int? UserId = request.UserId;
        if (!HasValue(UserId))
        {
            throw new InvalidOperationException("Parameter @UserId must be supplied by the request or a configured binding.");
        }
        bool? OnlyPreferred = request.OnlyPreferred;
        if (!HasValue(OnlyPreferred))
        {
            throw new InvalidOperationException("Parameter @OnlyPreferred must be supplied by the request or a configured binding.");
        }

        return new UserPreferredContactApplyInput(
            UserId,
            OnlyPreferred
        );
    }

    public static ValueTask<UserPreferredContactApplyInput> ToInputAsync(UserPreferredContactApplyRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class UserPreferredContactApplyPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@UserId", System.Data.DbType.Int32, 4, false, true),
            new("@OnlyPreferred", System.Data.DbType.Boolean, null, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "UserId"); int o1=ReaderUtil.TryGetOrdinal(r, "DisplayName"); int o2=ReaderUtil.TryGetOrdinal(r, "Email"); int o3=ReaderUtil.TryGetOrdinal(r, "IsActive"); int o4=ReaderUtil.TryGetOrdinal(r, "PreferredEmail"); int o5=ReaderUtil.TryGetOrdinal(r, "PreferredDisplayName"); int o6=ReaderUtil.TryGetOrdinal(r, "PreferredSource"); int o7=ReaderUtil.TryGetOrdinal(r, "PreferredLastInteractionUtc"); int o8=ReaderUtil.TryGetOrdinal(r, "PreferredRank"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserPreferredContactApplyResultSet1Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? string.Empty : (r.IsDBNull(o1) ? string.Empty : r.GetString(o1)), o2 < 0 ? null : (r.IsDBNull(o2) ? null : r.GetString(o2)), o3 < 0 ? default(bool) : r.GetBoolean(o3), o4 < 0 ? null : (r.IsDBNull(o4) ? null : r.GetString(o4)), o5 < 0 ? null : (r.IsDBNull(o5) ? null : r.GetString(o5)), o6 < 0 ? null : (r.IsDBNull(o6) ? null : r.GetString(o6)), o7 < 0 ? null : (r.IsDBNull(o7) ? null : (DateTime?)r.GetDateTime(o7)), o8 < 0 ? string.Empty : (r.IsDBNull(o8) ? string.Empty : r.GetString(o8)))); } return list;
			}),

            new("ResultSet2", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>();
                var __sb = new System.Text.StringBuilder();
                while (await r.ReadAsync(ct).ConfigureAwait(false))
                {
                    if (!r.IsDBNull(0))
                    {
                        __sb.Append(r.GetString(0));
                    }
                }
                var __raw = __sb.Length > 0 ? __sb.ToString() : null;
                var __items = new System.Collections.Generic.List<UserPreferredContactApplyResultSet2Result>();
                if (__raw != null)
                {
                    try
                    {
                        var __parsed = System.Text.Json.JsonSerializer.Deserialize<UserPreferredContactApplyResultSet2Result?>(__raw, JsonSupport.Options);
                        if (__parsed is { } __value)
                        {
                            __items.Add(__value);
                        }
                    }
                    catch
                    {
                    }
                }
                list.Add(JsonResultEnvelope<UserPreferredContactApplyResultSet2Result>.Create(__items, __raw));
                return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserPreferredContactApplyResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (UserPreferredContactApplyResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (UserPreferredContactApplyResultSet1Result)o).ToList() : Array.Empty<UserPreferredContactApplyResultSet1Result>()),
				// ResultSet 1 -> Result1
				Result1 = rs.Length > 1 && rs[1] is object[] rows1 && rows1.Length > 0 && rows1[0] is JsonResultEnvelope<UserPreferredContactApplyResultSet2Result> env1 && env1.TryGetFirst(out var value1) ? value1 : (UserPreferredContactApplyResultSet2Result?)null,
				Result1RawJson = rs.Length > 1 && rs[1] is object[] rows1_raw && rows1_raw.Length > 0 && rows1_raw[0] is JsonResultEnvelope<UserPreferredContactApplyResultSet2Result> env1_raw ? env1_raw.RawJson : null
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (UserPreferredContactApplyInput)state!;
			cmd.Parameters["@UserId"].Value = (object?)input.UserId ?? DBNull.Value;
			cmd.Parameters["@OnlyPreferred"].Value = (object?)input.OnlyPreferred ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[sample].[UserPreferredContactApply]", parameters, resultSets, OutputFactory, AggregateFactory, Binder, enableParameterBinding: false);
	}
}

/// <summary>Convenience extension for executing '[sample].[UserPreferredContactApply]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UserPreferredContactApplyExtensions
{
    public static async Task<UserPreferredContactApplyResult> UserPreferredContactApplyAsync(this IXtraqDbContext db, UserPreferredContactApplyRequest request, CancellationToken cancellationToken = default)
    {
        var bindingProvider = db as IXtraqParameterBindingProvider;
        var input = await UserPreferredContactApplyRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
        return await UserPreferredContactApplyAsync(db, input, cancellationToken).ConfigureAwait(false);
    }

	public static async Task<UserPreferredContactApplyResult> UserPreferredContactApplyAsync(this IXtraqDbContext db, UserPreferredContactApplyInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserPreferredContactApplyProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserPreferredContactApplyInput input, Func<UserPreferredContactApplyResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await UserPreferredContactApplyProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserPreferredContactApplyInput input, Func<UserPreferredContactApplyResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserPreferredContactApplyRequest request, Func<UserPreferredContactApplyResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await UserPreferredContactApplyRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		await StreamResultResultSet1Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
		return;
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserPreferredContactApplyRequest request, Func<UserPreferredContactApplyResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
	}

}

/// <summary>Minimal API extension for '[sample].[UserPreferredContactApply]'.</summary>
public static class UserPreferredContactApplyRouteHandlerBuilderExtensions
{
    public static RouteHandlerBuilder WithUserPreferredContactApplyProcedure(this RouteHandlerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithProcedure<UserPreferredContactApplyRequest, UserPreferredContactApplyResult>(
            static pipeline => pipeline.WithExecutor(
                static async ValueTask<UserPreferredContactApplyResult> (dbContext, request, cancellationToken) =>
                {
                    var bindingProvider = dbContext as IXtraqParameterBindingProvider;
                    var input = await UserPreferredContactApplyRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
                    return await UserPreferredContactApplyExtensions.UserPreferredContactApplyAsync(dbContext, input, cancellationToken).ConfigureAwait(false);
                }));
    }
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserPreferredContactApplyProcedure
{
	public const string Name = "[sample].[UserPreferredContactApply]";
	public static Task<UserPreferredContactApplyResult> ExecuteAsync(DbConnection connection, UserPreferredContactApplyInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<UserPreferredContactApplyResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserPreferredContactApplyInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<UserPreferredContactApplyResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserPreferredContactApplyInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserPreferredContactApplyResult>(interceptorProvider, bindingProvider, connection, UserPreferredContactApplyPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, UserPreferredContactApplyInput input, Func<UserPreferredContactApplyResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserPreferredContactApplyInput input, Func<UserPreferredContactApplyResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserPreferredContactApplyInput input, Func<UserPreferredContactApplyResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "UserId");
            int o1=ReaderUtil.TryGetOrdinal(reader, "DisplayName");
            int o2=ReaderUtil.TryGetOrdinal(reader, "Email");
            int o3=ReaderUtil.TryGetOrdinal(reader, "IsActive");
            int o4=ReaderUtil.TryGetOrdinal(reader, "PreferredEmail");
            int o5=ReaderUtil.TryGetOrdinal(reader, "PreferredDisplayName");
            int o6=ReaderUtil.TryGetOrdinal(reader, "PreferredSource");
            int o7=ReaderUtil.TryGetOrdinal(reader, "PreferredLastInteractionUtc");
            int o8=ReaderUtil.TryGetOrdinal(reader, "PreferredRank");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new UserPreferredContactApplyResultSet1Result(o0 < 0 ? default(int) : reader.GetInt32(o0), o1 < 0 ? string.Empty : (reader.IsDBNull(o1) ? string.Empty : reader.GetString(o1)), o2 < 0 ? null : (reader.IsDBNull(o2) ? null : reader.GetString(o2)), o3 < 0 ? default(bool) : reader.GetBoolean(o3), o4 < 0 ? null : (reader.IsDBNull(o4) ? null : reader.GetString(o4)), o5 < 0 ? null : (reader.IsDBNull(o5) ? null : reader.GetString(o5)), o6 < 0 ? null : (reader.IsDBNull(o6) ? null : reader.GetString(o6)), o7 < 0 ? null : (reader.IsDBNull(o7) ? null : (DateTime?)reader.GetDateTime(o7)), o8 < 0 ? string.Empty : (reader.IsDBNull(o8) ? string.Empty : reader.GetString(o8)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, UserPreferredContactApplyPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, UserPreferredContactApplyInput input, Func<UserPreferredContactApplyResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserPreferredContactApplyInput input, Func<UserPreferredContactApplyResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
