// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
#if NET8_0_OR_GREATER && XTRAQ_MINIMAL_API
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
#endif

/// <summary>
/// Represents the contract for the stored procedure <c>sample.UserCompositeJsonSnapshot</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for Minimal API / external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class UserCompositeJsonSnapshotRequest
{
    public int? UserId { get; init; }
    public int? RecentPaymentCount { get; init; }
}

public readonly record struct UserCompositeJsonSnapshotInput(
    int? UserId,
    int? RecentPaymentCount
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct UserCompositeJsonSnapshotResultSet1Result(
    string ProfileJson
);

/// <summary>
/// Represents the result set <c>ResultSet2</c> emitted by <c>sample.ResultSet2</c>.
/// </summary>
public readonly record struct UserCompositeJsonSnapshotResultSet2RecentPaymentsJsonResult(
    Guid PaymentId,
    string Gateway,
    decimal Amount,
    DateTime? CapturedAtUtc,
    System.Text.Json.Nodes.JsonNode? PropertiesJson
);
public readonly record struct UserCompositeJsonSnapshotResultSet2Result(
    int ContactId,
    string Email,
    string DisplayName,
    bool Preferred,
    DateTime? LastInteractionUtc,
    System.Collections.Generic.List<UserCompositeJsonSnapshotResultSet2RecentPaymentsJsonResult> RecentPaymentsJson
);

/// <summary>
/// Represents the result set <c>ResultSet3</c> emitted by <c>sample.ResultSet3</c>.
/// </summary>
public readonly record struct UserCompositeJsonSnapshotResultSet3Result(
    int OrderId,
    string OrderNumber,
    System.Text.Json.Nodes.JsonNode? MetadataJson
);

public sealed class UserCompositeJsonSnapshotResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserCompositeJsonSnapshotResultSet1Result> Result { get; init; } = Array.Empty<UserCompositeJsonSnapshotResultSet1Result>();
	/// <summary>
	/// Result set <c>ResultSet2</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserCompositeJsonSnapshotResultSet2Result> Result1 { get; init; } = Array.Empty<UserCompositeJsonSnapshotResultSet2Result>();
	/// <summary>
	/// Raw JSON payload captured for result set <c>ResultSet2</c>.
	/// </summary>
	public string? Result1RawJson { get; init; } = null;
	/// <summary>
	/// Result set <c>ResultSet3</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserCompositeJsonSnapshotResultSet3Result> Result2 { get; init; } = Array.Empty<UserCompositeJsonSnapshotResultSet3Result>();
	/// <summary>
	/// Raw JSON payload captured for result set <c>ResultSet3</c>.
	/// </summary>
	public string? Result2RawJson { get; init; } = null;
}

internal static class UserCompositeJsonSnapshotRequestMapper
{
    public static async ValueTask<UserCompositeJsonSnapshotInput> ToInputAsync(UserCompositeJsonSnapshotRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new UserCompositeJsonSnapshotRequest();
        var UserId = request.UserId;
        if (!HasValue(UserId))
        {
            UserId = await ResolveAsync<int?>(bindingProvider, "[sample].[UserCompositeJsonSnapshot]", "@UserId", false, UserId, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(UserId))
        {
            throw new InvalidOperationException("Parameter @UserId must be supplied by the request or a configured binding.");
        }
        var RecentPaymentCount = request.RecentPaymentCount;
        if (!HasValue(RecentPaymentCount))
        {
            RecentPaymentCount = await ResolveAsync<int?>(bindingProvider, "[sample].[UserCompositeJsonSnapshot]", "@RecentPaymentCount", false, RecentPaymentCount, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(RecentPaymentCount))
        {
            throw new InvalidOperationException("Parameter @RecentPaymentCount must be supplied by the request or a configured binding.");
        }

        return new UserCompositeJsonSnapshotInput(
            UserId,
            RecentPaymentCount
        );
    }

    public static ValueTask<UserCompositeJsonSnapshotInput> ToInputAsync(UserCompositeJsonSnapshotRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class UserCompositeJsonSnapshotPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@UserId", System.Data.DbType.Int32, null, false, true),
            new("@RecentPaymentCount", System.Data.DbType.Int32, null, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "ProfileJson"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserCompositeJsonSnapshotResultSet1Result(o0 < 0 ? string.Empty : (r.IsDBNull(o0) ? string.Empty : r.GetString(o0)))); } return list;
			}),

            new("ResultSet2", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>();
                var __sb = new System.Text.StringBuilder();
                while (await r.ReadAsync(ct).ConfigureAwait(false))
                {
                    if (!r.IsDBNull(0))
                    {
                        __sb.Append(r.GetString(0));
                    }
                }
                var __raw = __sb.Length > 0 ? __sb.ToString() : null;
                var __items = new System.Collections.Generic.List<UserCompositeJsonSnapshotResultSet2Result>();
                if (__raw != null)
                {
                    try
                    {
                        var __parsed = System.Text.Json.JsonSerializer.Deserialize<System.Collections.Generic.List<UserCompositeJsonSnapshotResultSet2Result?>>(__raw, JsonSupport.Options);
                        if (__parsed is not null)
                        {
                            foreach (var __entry in __parsed)
                            {
                                if (__entry is { } __value)
                                {
                                    __items.Add(__value);
                                }
                            }
                        }
                    }
                    catch
                    {
                    }
                }
                list.Add(JsonResultEnvelope<UserCompositeJsonSnapshotResultSet2Result>.Create(__items, __raw));
                return list;
			}),

            new("ResultSet3", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>();
                var __sb = new System.Text.StringBuilder();
                while (await r.ReadAsync(ct).ConfigureAwait(false))
                {
                    if (!r.IsDBNull(0))
                    {
                        __sb.Append(r.GetString(0));
                    }
                }
                var __raw = __sb.Length > 0 ? __sb.ToString() : null;
                var __items = new System.Collections.Generic.List<UserCompositeJsonSnapshotResultSet3Result>();
                if (__raw != null)
                {
                    try
                    {
                        var __parsed = System.Text.Json.JsonSerializer.Deserialize<System.Collections.Generic.List<UserCompositeJsonSnapshotResultSet3Result?>>(__raw, JsonSupport.Options);
                        if (__parsed is not null)
                        {
                            foreach (var __entry in __parsed)
                            {
                                if (__entry is { } __value)
                                {
                                    __items.Add(__value);
                                }
                            }
                        }
                    }
                    catch
                    {
                    }
                }
                list.Add(JsonResultEnvelope<UserCompositeJsonSnapshotResultSet3Result>.Create(__items, __raw));
                return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserCompositeJsonSnapshotResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (UserCompositeJsonSnapshotResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (UserCompositeJsonSnapshotResultSet1Result)o).ToList() : Array.Empty<UserCompositeJsonSnapshotResultSet1Result>()),
				// ResultSet 1 -> Result1
				Result1 = rs.Length > 1 && rs[1] is object[] rows1 && rows1.Length > 0 && rows1[0] is JsonResultEnvelope<UserCompositeJsonSnapshotResultSet2Result> env1 ? env1.Items : System.Array.Empty<UserCompositeJsonSnapshotResultSet2Result>(),
				Result1RawJson = rs.Length > 1 && rs[1] is object[] rows1_raw && rows1_raw.Length > 0 && rows1_raw[0] is JsonResultEnvelope<UserCompositeJsonSnapshotResultSet2Result> env1_raw ? env1_raw.RawJson : null,
				// ResultSet 2 -> Result2
				Result2 = rs.Length > 2 && rs[2] is object[] rows2 && rows2.Length > 0 && rows2[0] is JsonResultEnvelope<UserCompositeJsonSnapshotResultSet3Result> env2 ? env2.Items : System.Array.Empty<UserCompositeJsonSnapshotResultSet3Result>(),
				Result2RawJson = rs.Length > 2 && rs[2] is object[] rows2_raw && rows2_raw.Length > 0 && rows2_raw[0] is JsonResultEnvelope<UserCompositeJsonSnapshotResultSet3Result> env2_raw ? env2_raw.RawJson : null
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (UserCompositeJsonSnapshotInput)state!;
			cmd.Parameters["@UserId"].Value = (object?)input.UserId ?? DBNull.Value;
			cmd.Parameters["@RecentPaymentCount"].Value = (object?)input.RecentPaymentCount ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[sample].[UserCompositeJsonSnapshot]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[UserCompositeJsonSnapshot]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UserCompositeJsonSnapshotExtensions
{
    public static async Task<UserCompositeJsonSnapshotResult> UserCompositeJsonSnapshotAsync(this IXtraqDbContext db, UserCompositeJsonSnapshotRequest request, CancellationToken cancellationToken = default)
    {
        var bindingProvider = db as IXtraqParameterBindingProvider;
        var input = await UserCompositeJsonSnapshotRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
        return await UserCompositeJsonSnapshotAsync(db, input, cancellationToken).ConfigureAwait(false);
    }

	public static async Task<UserCompositeJsonSnapshotResult> UserCompositeJsonSnapshotAsync(this IXtraqDbContext db, UserCompositeJsonSnapshotInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserCompositeJsonSnapshotProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserCompositeJsonSnapshotInput input, Func<UserCompositeJsonSnapshotResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await UserCompositeJsonSnapshotProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserCompositeJsonSnapshotInput input, Func<UserCompositeJsonSnapshotResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

    /// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
    public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserCompositeJsonSnapshotRequest request, Func<UserCompositeJsonSnapshotResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(db);
        ArgumentNullException.ThrowIfNull(onRowAsync);
        var bindingProvider = db as IXtraqParameterBindingProvider;
        var input = await UserCompositeJsonSnapshotRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
        await StreamResultResultSet1Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
        return;
    }

    /// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
    public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserCompositeJsonSnapshotRequest request, Func<UserCompositeJsonSnapshotResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(onRowAsync);
        return StreamResultResultSet1Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
    }

}

#if NET8_0_OR_GREATER && XTRAQ_MINIMAL_API
/// <summary>Minimal API extension for '[sample].[UserCompositeJsonSnapshot]'.</summary>
public static class UserCompositeJsonSnapshotRouteHandlerBuilderExtensions
{
    public static RouteHandlerBuilder WithUserCompositeJsonSnapshotProcedure(this RouteHandlerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithProcedure<UserCompositeJsonSnapshotRequest, UserCompositeJsonSnapshotResult>(
            static pipeline => pipeline.WithExecutor(
                static async ValueTask<UserCompositeJsonSnapshotResult> (dbContext, request, cancellationToken) =>
                {
                    var bindingProvider = dbContext as IXtraqParameterBindingProvider;
                    var input = await UserCompositeJsonSnapshotRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
                    return await UserCompositeJsonSnapshotExtensions.UserCompositeJsonSnapshotAsync(dbContext, input, cancellationToken).ConfigureAwait(false);
                }));
    }
}
#endif

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserCompositeJsonSnapshotProcedure
{
	public const string Name = "[sample].[UserCompositeJsonSnapshot]";
	public static Task<UserCompositeJsonSnapshotResult> ExecuteAsync(DbConnection connection, UserCompositeJsonSnapshotInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<UserCompositeJsonSnapshotResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserCompositeJsonSnapshotInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<UserCompositeJsonSnapshotResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserCompositeJsonSnapshotInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserCompositeJsonSnapshotResult>(interceptorProvider, bindingProvider, connection, UserCompositeJsonSnapshotPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, UserCompositeJsonSnapshotInput input, Func<UserCompositeJsonSnapshotResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserCompositeJsonSnapshotInput input, Func<UserCompositeJsonSnapshotResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserCompositeJsonSnapshotInput input, Func<UserCompositeJsonSnapshotResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "ProfileJson");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new UserCompositeJsonSnapshotResultSet1Result(o0 < 0 ? string.Empty : (reader.IsDBNull(o0) ? string.Empty : reader.GetString(o0)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, UserCompositeJsonSnapshotPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, UserCompositeJsonSnapshotInput input, Func<UserCompositeJsonSnapshotResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserCompositeJsonSnapshotInput input, Func<UserCompositeJsonSnapshotResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
