// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.UserFind</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
public readonly record struct UserFindInput(
    int? UserId
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct UserFindResultSet1Result(
    int UserId,
    string? Alias,
    string DisplayName,
    string? Email,
    bool IsActive,
    string PreferredLocale,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc,
    string PreferredContactEmail,
    string PreferredContactDisplayName
);

public sealed class UserFindResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserFindResultSet1Result> Result { get; init; } = Array.Empty<UserFindResultSet1Result>();
}

internal static partial class UserFindPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@UserId", System.Data.DbType.Int32, null, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "UserId"); int o1=ReaderUtil.TryGetOrdinal(r, "Alias"); int o2=ReaderUtil.TryGetOrdinal(r, "DisplayName"); int o3=ReaderUtil.TryGetOrdinal(r, "Email"); int o4=ReaderUtil.TryGetOrdinal(r, "IsActive"); int o5=ReaderUtil.TryGetOrdinal(r, "PreferredLocale"); int o6=ReaderUtil.TryGetOrdinal(r, "CreatedAtUtc"); int o7=ReaderUtil.TryGetOrdinal(r, "UpdatedAtUtc"); int o8=ReaderUtil.TryGetOrdinal(r, "PreferredContactEmail"); int o9=ReaderUtil.TryGetOrdinal(r, "PreferredContactDisplayName"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserFindResultSet1Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? null : (r.IsDBNull(o1) ? null : r.GetString(o1)), o2 < 0 ? string.Empty : (r.IsDBNull(o2) ? string.Empty : r.GetString(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : r.GetString(o3)), o4 < 0 ? default(bool) : r.GetBoolean(o4), o5 < 0 ? string.Empty : (r.IsDBNull(o5) ? string.Empty : r.GetString(o5)), o6 < 0 ? default(DateTime) : r.GetDateTime(o6), o7 < 0 ? null : (r.IsDBNull(o7) ? null : (DateTime?)r.GetDateTime(o7)), o8 < 0 ? string.Empty : (r.IsDBNull(o8) ? string.Empty : r.GetString(o8)), o9 < 0 ? string.Empty : (r.IsDBNull(o9) ? string.Empty : r.GetString(o9)))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserFindResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (UserFindResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (UserFindResultSet1Result)o).ToList() : Array.Empty<UserFindResultSet1Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (UserFindInput)state!;
			cmd.Parameters["@UserId"].Value = input.UserId;
		}
		return new ProcedureExecutionPlan(
			"[sample].[UserFind]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[UserFind]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UserFindExtensions
{
	public static async Task<UserFindResult> UserFindAsync(this IXtraqDbContext db, UserFindInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserFindProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserFindInput input, Func<UserFindResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await UserFindProcedure.StreamResultResultSet1Async(connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserFindInput input, Func<UserFindResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserFindProcedure
{
	public const string Name = "[sample].[UserFind]";
	public static Task<UserFindResult> ExecuteAsync(DbConnection connection, UserFindInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserFindResult>(connection, UserFindPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static async Task StreamResultResultSet1Async(DbConnection connection, UserFindInput input, Func<UserFindResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "UserId");
            int o1=ReaderUtil.TryGetOrdinal(reader, "Alias");
            int o2=ReaderUtil.TryGetOrdinal(reader, "DisplayName");
            int o3=ReaderUtil.TryGetOrdinal(reader, "Email");
            int o4=ReaderUtil.TryGetOrdinal(reader, "IsActive");
            int o5=ReaderUtil.TryGetOrdinal(reader, "PreferredLocale");
            int o6=ReaderUtil.TryGetOrdinal(reader, "CreatedAtUtc");
            int o7=ReaderUtil.TryGetOrdinal(reader, "UpdatedAtUtc");
            int o8=ReaderUtil.TryGetOrdinal(reader, "PreferredContactEmail");
            int o9=ReaderUtil.TryGetOrdinal(reader, "PreferredContactDisplayName");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new UserFindResultSet1Result(o0 < 0 ? default(int) : reader.GetInt32(o0), o1 < 0 ? null : (reader.IsDBNull(o1) ? null : reader.GetString(o1)), o2 < 0 ? string.Empty : (reader.IsDBNull(o2) ? string.Empty : reader.GetString(o2)), o3 < 0 ? null : (reader.IsDBNull(o3) ? null : reader.GetString(o3)), o4 < 0 ? default(bool) : reader.GetBoolean(o4), o5 < 0 ? string.Empty : (reader.IsDBNull(o5) ? string.Empty : reader.GetString(o5)), o6 < 0 ? default(DateTime) : reader.GetDateTime(o6), o7 < 0 ? null : (reader.IsDBNull(o7) ? null : (DateTime?)reader.GetDateTime(o7)), o8 < 0 ? string.Empty : (reader.IsDBNull(o8) ? string.Empty : reader.GetString(o8)), o9 < 0 ? string.Empty : (reader.IsDBNull(o9) ? string.Empty : reader.GetString(o9)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(connection, UserFindPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, UserFindInput input, Func<UserFindResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
