// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
#if NET8_0_OR_GREATER && XTRAQ_API_MODE_MINIMAL
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
#endif

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.UserList</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for Minimal API / external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class UserListRequest
{
    public bool? IncludeInactive { get; init; }
}

public readonly record struct UserListInput(
    bool IncludeInactive
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct UserListResultSet1Result(
    int UserId,
    string? Alias,
    string DisplayName,
    string? Email,
    bool IsActive,
    string PreferredLocale,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc,
    string SearchName
);

public sealed class UserListResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserListResultSet1Result> Result { get; init; } = Array.Empty<UserListResultSet1Result>();
}

internal static class UserListRequestMapper
{
    public static async ValueTask<UserListInput> ToInputAsync(UserListRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new UserListRequest();
        var IncludeInactive = request.IncludeInactive;
        if (!HasValue(IncludeInactive))
        {
            throw new InvalidOperationException("Parameter @IncludeInactive must be supplied by the request or a configured binding.");
        }

        return new UserListInput(
            IncludeInactive ?? default
        );
    }

    public static ValueTask<UserListInput> ToInputAsync(UserListRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class UserListPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@IncludeInactive", System.Data.DbType.Boolean, null, false, false),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "UserId"); int o1=ReaderUtil.TryGetOrdinal(r, "Alias"); int o2=ReaderUtil.TryGetOrdinal(r, "DisplayName"); int o3=ReaderUtil.TryGetOrdinal(r, "Email"); int o4=ReaderUtil.TryGetOrdinal(r, "IsActive"); int o5=ReaderUtil.TryGetOrdinal(r, "PreferredLocale"); int o6=ReaderUtil.TryGetOrdinal(r, "CreatedAtUtc"); int o7=ReaderUtil.TryGetOrdinal(r, "UpdatedAtUtc"); int o8=ReaderUtil.TryGetOrdinal(r, "SearchName"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserListResultSet1Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? null : (r.IsDBNull(o1) ? null : r.GetString(o1)), o2 < 0 ? string.Empty : (r.IsDBNull(o2) ? string.Empty : r.GetString(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : r.GetString(o3)), o4 < 0 ? default(bool) : r.GetBoolean(o4), o5 < 0 ? string.Empty : (r.IsDBNull(o5) ? string.Empty : r.GetString(o5)), o6 < 0 ? default(DateTime) : r.GetDateTime(o6), o7 < 0 ? null : (r.IsDBNull(o7) ? null : (DateTime?)r.GetDateTime(o7)), o8 < 0 ? string.Empty : (r.IsDBNull(o8) ? string.Empty : r.GetString(o8)))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserListResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (UserListResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (UserListResultSet1Result)o).ToList() : Array.Empty<UserListResultSet1Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (UserListInput)state!;
			cmd.Parameters["@IncludeInactive"].Value = input.IncludeInactive;
		}
		return new ProcedureExecutionPlan(
			"[sample].[UserList]", parameters, resultSets, OutputFactory, AggregateFactory, Binder, enableParameterBinding: false);
	}
}

/// <summary>Convenience extension for executing '[sample].[UserList]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UserListExtensions
{
    public static async Task<UserListResult> UserListAsync(this IXtraqDbContext db, UserListRequest request, CancellationToken cancellationToken = default)
    {
        var bindingProvider = db as IXtraqParameterBindingProvider;
        var input = await UserListRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
        return await UserListAsync(db, input, cancellationToken).ConfigureAwait(false);
    }

	public static async Task<UserListResult> UserListAsync(this IXtraqDbContext db, UserListInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserListProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserListInput input, Func<UserListResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await UserListProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserListInput input, Func<UserListResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

    /// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
    public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserListRequest request, Func<UserListResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(db);
        ArgumentNullException.ThrowIfNull(onRowAsync);
        var bindingProvider = db as IXtraqParameterBindingProvider;
        var input = await UserListRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
        await StreamResultResultSet1Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
        return;
    }

    /// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
    public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserListRequest request, Func<UserListResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(onRowAsync);
        return StreamResultResultSet1Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
    }

}

#if NET8_0_OR_GREATER && XTRAQ_API_MODE_MINIMAL
/// <summary>Minimal API extension for '[sample].[UserList]'.</summary>
public static class UserListRouteHandlerBuilderExtensions
{
    public static RouteHandlerBuilder WithUserListProcedure(this RouteHandlerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithProcedure<UserListRequest, UserListResult>(
            static pipeline => pipeline.WithExecutor(
                static async ValueTask<UserListResult> (dbContext, request, cancellationToken) =>
                {
                    var bindingProvider = dbContext as IXtraqParameterBindingProvider;
                    var input = await UserListRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
                    return await UserListExtensions.UserListAsync(dbContext, input, cancellationToken).ConfigureAwait(false);
                }));
    }
}
#endif

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserListProcedure
{
	public const string Name = "[sample].[UserList]";
	public static Task<UserListResult> ExecuteAsync(DbConnection connection, UserListInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<UserListResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserListInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<UserListResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserListInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserListResult>(interceptorProvider, bindingProvider, connection, UserListPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, UserListInput input, Func<UserListResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserListInput input, Func<UserListResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserListInput input, Func<UserListResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "UserId");
            int o1=ReaderUtil.TryGetOrdinal(reader, "Alias");
            int o2=ReaderUtil.TryGetOrdinal(reader, "DisplayName");
            int o3=ReaderUtil.TryGetOrdinal(reader, "Email");
            int o4=ReaderUtil.TryGetOrdinal(reader, "IsActive");
            int o5=ReaderUtil.TryGetOrdinal(reader, "PreferredLocale");
            int o6=ReaderUtil.TryGetOrdinal(reader, "CreatedAtUtc");
            int o7=ReaderUtil.TryGetOrdinal(reader, "UpdatedAtUtc");
            int o8=ReaderUtil.TryGetOrdinal(reader, "SearchName");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new UserListResultSet1Result(o0 < 0 ? default(int) : reader.GetInt32(o0), o1 < 0 ? null : (reader.IsDBNull(o1) ? null : reader.GetString(o1)), o2 < 0 ? string.Empty : (reader.IsDBNull(o2) ? string.Empty : reader.GetString(o2)), o3 < 0 ? null : (reader.IsDBNull(o3) ? null : reader.GetString(o3)), o4 < 0 ? default(bool) : reader.GetBoolean(o4), o5 < 0 ? string.Empty : (reader.IsDBNull(o5) ? string.Empty : reader.GetString(o5)), o6 < 0 ? default(DateTime) : reader.GetDateTime(o6), o7 < 0 ? null : (reader.IsDBNull(o7) ? null : (DateTime?)reader.GetDateTime(o7)), o8 < 0 ? string.Empty : (reader.IsDBNull(o8) ? string.Empty : reader.GetString(o8)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, UserListPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, UserListInput input, Func<UserListResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserListInput input, Func<UserListResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
