// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.UserOrderJoinDiagnostics</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class UserOrderJoinDiagnosticsRequest
{
    public int? UserId { get; init; }
}

public readonly record struct UserOrderJoinDiagnosticsInput(
    int? UserId
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct UserOrderJoinDiagnosticsResultSet1Result(
    int OrderId,
    string OrderNumber,
    string Status,
    string? PublicNote,
    bool? NoteIsPublic
);

/// <summary>
/// Represents the result set <c>ResultSet2</c> emitted by <c>sample.ResultSet2</c>.
/// </summary>
public readonly record struct UserOrderJoinDiagnosticsResultSet2Result(
    int OrderId,
    string OrderNumber,
    string? PrimaryTag,
    bool? IsPrimary
);

public sealed class UserOrderJoinDiagnosticsResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserOrderJoinDiagnosticsResultSet1Result> Result { get; init; } = Array.Empty<UserOrderJoinDiagnosticsResultSet1Result>();
	/// <summary>
	/// Result set <c>ResultSet2</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserOrderJoinDiagnosticsResultSet2Result> Result1 { get; init; } = Array.Empty<UserOrderJoinDiagnosticsResultSet2Result>();
}
internal static class UserOrderJoinDiagnosticsRequestMapper
{
    public static async ValueTask<UserOrderJoinDiagnosticsInput> ToInputAsync(UserOrderJoinDiagnosticsRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new UserOrderJoinDiagnosticsRequest();
        int? UserId = request.UserId;

        return new UserOrderJoinDiagnosticsInput(
            UserId
        );
    }

    public static ValueTask<UserOrderJoinDiagnosticsInput> ToInputAsync(UserOrderJoinDiagnosticsRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class UserOrderJoinDiagnosticsPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@UserId", System.Data.DbType.Int32, 4, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "OrderId"); int o1=ReaderUtil.TryGetOrdinal(r, "OrderNumber"); int o2=ReaderUtil.TryGetOrdinal(r, "Status"); int o3=ReaderUtil.TryGetOrdinal(r, "PublicNote"); int o4=ReaderUtil.TryGetOrdinal(r, "NoteIsPublic"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserOrderJoinDiagnosticsResultSet1Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? string.Empty : (r.IsDBNull(o1) ? string.Empty : r.GetString(o1)), o2 < 0 ? string.Empty : (r.IsDBNull(o2) ? string.Empty : r.GetString(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : r.GetString(o3)), o4 < 0 ? null : (r.IsDBNull(o4) ? null : (bool?)r.GetBoolean(o4)))); } return list;
			}),

            new("ResultSet2", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "OrderId"); int o1=ReaderUtil.TryGetOrdinal(r, "OrderNumber"); int o2=ReaderUtil.TryGetOrdinal(r, "PrimaryTag"); int o3=ReaderUtil.TryGetOrdinal(r, "IsPrimary"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserOrderJoinDiagnosticsResultSet2Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? string.Empty : (r.IsDBNull(o1) ? string.Empty : r.GetString(o1)), o2 < 0 ? null : (r.IsDBNull(o2) ? null : r.GetString(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : (bool?)r.GetBoolean(o3)))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserOrderJoinDiagnosticsResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (UserOrderJoinDiagnosticsResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (UserOrderJoinDiagnosticsResultSet1Result)o).ToList() : Array.Empty<UserOrderJoinDiagnosticsResultSet1Result>()),
				// ResultSet 1 -> Result1
				Result1 = rs.Length > 1 && rs[1] is object[] rows1 ? Array.ConvertAll(rows1, o => (UserOrderJoinDiagnosticsResultSet2Result)o).ToList() : (rs.Length > 1 && rs[1] is System.Collections.Generic.List<object> list1 ? Array.ConvertAll(list1.ToArray(), o => (UserOrderJoinDiagnosticsResultSet2Result)o).ToList() : Array.Empty<UserOrderJoinDiagnosticsResultSet2Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (UserOrderJoinDiagnosticsInput)state!;
			cmd.Parameters["@UserId"].Value = (object?)input.UserId ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[sample].[UserOrderJoinDiagnostics]", parameters, resultSets, OutputFactory, AggregateFactory, Binder, enableParameterBinding: false);
	}
}

/// <summary>Convenience extension for executing '[sample].[UserOrderJoinDiagnostics]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UserOrderJoinDiagnosticsExtensions
{
	public static async Task<UserOrderJoinDiagnosticsResult> UserOrderJoinDiagnosticsAsync(this IXtraqDbContext db, UserOrderJoinDiagnosticsRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await UserOrderJoinDiagnosticsRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await UserOrderJoinDiagnosticsAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<UserOrderJoinDiagnosticsResult> UserOrderJoinDiagnosticsAsync(this IXtraqDbContext db, UserOrderJoinDiagnosticsInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserOrderJoinDiagnosticsProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await UserOrderJoinDiagnosticsProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserOrderJoinDiagnosticsRequest request, Func<UserOrderJoinDiagnosticsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await UserOrderJoinDiagnosticsRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		await StreamResultResultSet1Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
		return;
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserOrderJoinDiagnosticsRequest request, Func<UserOrderJoinDiagnosticsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet2</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet2Async(this IXtraqDbContext db, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet2Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await UserOrderJoinDiagnosticsProcedure.StreamResultResultSet2Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet2Async(this IXtraqDbContext db, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet2Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet2Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet2</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static async Task StreamResultResultSet2Async(this IXtraqDbContext db, UserOrderJoinDiagnosticsRequest request, Func<UserOrderJoinDiagnosticsResultSet2Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await UserOrderJoinDiagnosticsRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		await StreamResultResultSet2Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
		return;
	}

	/// <summary>Streams result set <c>ResultSet2</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static Task StreamResultResultSet2Async(this IXtraqDbContext db, UserOrderJoinDiagnosticsRequest request, Func<UserOrderJoinDiagnosticsResultSet2Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet2Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserOrderJoinDiagnosticsProcedure
{
	public const string Name = "[sample].[UserOrderJoinDiagnostics]";
	public static Task<UserOrderJoinDiagnosticsResult> ExecuteAsync(DbConnection connection, UserOrderJoinDiagnosticsInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<UserOrderJoinDiagnosticsResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserOrderJoinDiagnosticsInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<UserOrderJoinDiagnosticsResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserOrderJoinDiagnosticsInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserOrderJoinDiagnosticsResult>(interceptorProvider, bindingProvider, connection, UserOrderJoinDiagnosticsPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "OrderId");
            int o1=ReaderUtil.TryGetOrdinal(reader, "OrderNumber");
            int o2=ReaderUtil.TryGetOrdinal(reader, "Status");
            int o3=ReaderUtil.TryGetOrdinal(reader, "PublicNote");
            int o4=ReaderUtil.TryGetOrdinal(reader, "NoteIsPublic");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new UserOrderJoinDiagnosticsResultSet1Result(o0 < 0 ? default(int) : reader.GetInt32(o0), o1 < 0 ? string.Empty : (reader.IsDBNull(o1) ? string.Empty : reader.GetString(o1)), o2 < 0 ? string.Empty : (reader.IsDBNull(o2) ? string.Empty : reader.GetString(o2)), o3 < 0 ? null : (reader.IsDBNull(o3) ? null : reader.GetString(o3)), o4 < 0 ? null : (reader.IsDBNull(o4) ? null : (bool?)reader.GetBoolean(o4)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, UserOrderJoinDiagnosticsPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet2</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet2Async(DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet2Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet2Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet2Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet2Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet2Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet2Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet2Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "OrderId");
            int o1=ReaderUtil.TryGetOrdinal(reader, "OrderNumber");
            int o2=ReaderUtil.TryGetOrdinal(reader, "PrimaryTag");
            int o3=ReaderUtil.TryGetOrdinal(reader, "IsPrimary");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new UserOrderJoinDiagnosticsResultSet2Result(o0 < 0 ? default(int) : reader.GetInt32(o0), o1 < 0 ? string.Empty : (reader.IsDBNull(o1) ? string.Empty : reader.GetString(o1)), o2 < 0 ? null : (reader.IsDBNull(o2) ? null : reader.GetString(o2)), o3 < 0 ? null : (reader.IsDBNull(o3) ? null : (bool?)reader.GetBoolean(o3)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, UserOrderJoinDiagnosticsPlan.Instance, 1, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet2Async(DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet2Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet2Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet2Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserOrderJoinDiagnosticsInput input, Func<UserOrderJoinDiagnosticsResultSet2Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet2Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
