// <auto-generated/>
// Xtraq Code Generator v1.0.0-alpha.6. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using System;
#if XTRAQ_ENABLE_TABLETYPE_VALIDATION
using FluentValidation;
#endif

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Sample.UserContactTableType</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record UserContactTableType : ITableType
{
    public int UserId { get; init; }
    public string Email { get; init; } = string.Empty;
    public string DisplayName { get; init; } = string.Empty;
    public string? Source { get; init; }
    public bool? Preferred { get; init; }
    public DateTime? LastInteractionUtc { get; init; }
#if XTRAQ_ENFORCE_TABLETYPE_BUILDER
	#warning Use the 'UserContactTableTypeBuilder' or factory method instead of object initializers.
#endif

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public UserContactTableType() { }

	public static UserContactTableType Create(
        int UserId,
        string Email,
        string DisplayName,
        string? Source,
        bool? Preferred,
        DateTime? LastInteractionUtc
    ) =>
	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
	new UserContactTableType
	{
        UserId = UserId,
        Email = Email,
        DisplayName = DisplayName,
        Source = Source,
        Preferred = Preferred,
        LastInteractionUtc = LastInteractionUtc
    };
	#pragma warning restore CS0612, CS0618

	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class UserContactTableTypeBuilder
	{
        private int _UserId;
        private string _Email = string.Empty;
        private string _DisplayName = string.Empty;
        private string? _Source;
        private bool? _Preferred;
        private DateTime? _LastInteractionUtc;
        public UserContactTableTypeBuilder WithUserId(int value) { _UserId = value; return this; }
        public UserContactTableTypeBuilder WithEmail(string value) { _Email = value; return this; }
        public UserContactTableTypeBuilder WithDisplayName(string value) { _DisplayName = value; return this; }
        public UserContactTableTypeBuilder WithSource(string? value) { _Source = value; return this; }
        public UserContactTableTypeBuilder WithPreferred(bool? value) { _Preferred = value; return this; }
        public UserContactTableTypeBuilder WithLastInteractionUtc(DateTime? value) { _LastInteractionUtc = value; return this; }
        public UserContactTableType Build()
        {
			#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
			var result = new UserContactTableType
            {
                UserId = _UserId,
                Email = _Email,
                DisplayName = _DisplayName,
                Source = _Source,
                Preferred = _Preferred,
                LastInteractionUtc = _LastInteractionUtc
            };
			#pragma warning restore CS0612, CS0618
#if XTRAQ_ENABLE_TABLETYPE_VALIDATION
            UserContactTableTypeValidator.Instance.ValidateAndThrow(result);
#endif
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
#if XTRAQ_ENABLE_TABLETYPE_VALIDATION
	private sealed class UserContactTableTypeValidator : AbstractValidator<UserContactTableType>
	{
		public static readonly UserContactTableTypeValidator Instance = new();
		public UserContactTableTypeValidator()
		{
			// Add rules (placeholder - extend generator to emit rules per column metadata, e.g. nullability / max length)
			// Example: RuleFor(x => x.SomeColumn).NotNull();
		}
	}
#endif
}
