// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.UserOrderInsights</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class UserOrderInsightsRequest
{
    public int? UserId { get; init; }
}

public readonly record struct UserOrderInsightsInput(
    int? UserId
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>sample.ResultSet1</c>.
/// </summary>
public readonly record struct UserOrderInsightsResultSet1Result(
    int UserId,
    string DisplayName,
    string? LatestOrderNumber,
    decimal? LatestOrderTotalAmount,
    string? LatestOrderCurrency,
    DateTime? LatestOrderRequiredAtUtc,
    string? LatestOrderMetadata,
    long? PendingOrderCount,
    decimal? CapturedPaymentAmount,
    Guid? CapturedPaymentCount,
    DateTime? NextContactReminderUtc
);

public sealed class UserOrderInsightsResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<UserOrderInsightsResultSet1Result> Result { get; init; } = Array.Empty<UserOrderInsightsResultSet1Result>();
}

internal static class UserOrderInsightsRequestMapper
{
    public static async ValueTask<UserOrderInsightsInput> ToInputAsync(UserOrderInsightsRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new UserOrderInsightsRequest();
        int? UserId = request.UserId;
        if (!HasValue(UserId))
        {
            throw new InvalidOperationException("Parameter @UserId must be supplied by the request or a configured binding.");
        }

        return new UserOrderInsightsInput(
            UserId
        );
    }

    public static ValueTask<UserOrderInsightsInput> ToInputAsync(UserOrderInsightsRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class UserOrderInsightsPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@UserId", System.Data.DbType.Int32, 4, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "UserId"); int o1=ReaderUtil.TryGetOrdinal(r, "DisplayName"); int o2=ReaderUtil.TryGetOrdinal(r, "LatestOrderNumber"); int o3=ReaderUtil.TryGetOrdinal(r, "LatestOrderTotalAmount"); int o4=ReaderUtil.TryGetOrdinal(r, "LatestOrderCurrency"); int o5=ReaderUtil.TryGetOrdinal(r, "LatestOrderRequiredAtUtc"); int o6=ReaderUtil.TryGetOrdinal(r, "LatestOrderMetadata"); int o7=ReaderUtil.TryGetOrdinal(r, "PendingOrderCount"); int o8=ReaderUtil.TryGetOrdinal(r, "CapturedPaymentAmount"); int o9=ReaderUtil.TryGetOrdinal(r, "CapturedPaymentCount"); int o10=ReaderUtil.TryGetOrdinal(r, "NextContactReminderUtc"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserOrderInsightsResultSet1Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? string.Empty : (r.IsDBNull(o1) ? string.Empty : r.GetString(o1)), o2 < 0 ? null : (r.IsDBNull(o2) ? null : r.GetString(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : (decimal?)r.GetDecimal(o3)), o4 < 0 ? null : (r.IsDBNull(o4) ? null : r.GetString(o4)), o5 < 0 ? null : (r.IsDBNull(o5) ? null : (DateTime?)r.GetDateTime(o5)), o6 < 0 ? null : (r.IsDBNull(o6) ? null : r.GetString(o6)), o7 < 0 ? null : (r.IsDBNull(o7) ? null : (long?)r.GetInt64(o7)), o8 < 0 ? null : (r.IsDBNull(o8) ? null : (decimal?)r.GetDecimal(o8)), o9 < 0 ? null : (r.IsDBNull(o9) ? null : (Guid?)r.GetGuid(o9)), o10 < 0 ? null : (r.IsDBNull(o10) ? null : (DateTime?)r.GetDateTime(o10)))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserOrderInsightsResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (UserOrderInsightsResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (UserOrderInsightsResultSet1Result)o).ToList() : Array.Empty<UserOrderInsightsResultSet1Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (UserOrderInsightsInput)state!;
			cmd.Parameters["@UserId"].Value = (object?)input.UserId ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[sample].[UserOrderInsights]", parameters, resultSets, OutputFactory, AggregateFactory, Binder, enableParameterBinding: false);
	}
}

/// <summary>Convenience extension for executing '[sample].[UserOrderInsights]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class UserOrderInsightsExtensions
{
	public static async Task<UserOrderInsightsResult> UserOrderInsightsAsync(this IXtraqDbContext db, UserOrderInsightsRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await UserOrderInsightsRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await UserOrderInsightsAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<UserOrderInsightsResult> UserOrderInsightsAsync(this IXtraqDbContext db, UserOrderInsightsInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserOrderInsightsProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserOrderInsightsInput input, Func<UserOrderInsightsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await UserOrderInsightsProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserOrderInsightsInput input, Func<UserOrderInsightsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, UserOrderInsightsRequest request, Func<UserOrderInsightsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await UserOrderInsightsRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		await StreamResultResultSet1Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
		return;
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, UserOrderInsightsRequest request, Func<UserOrderInsightsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserOrderInsightsProcedure
{
	public const string Name = "[sample].[UserOrderInsights]";
	public static Task<UserOrderInsightsResult> ExecuteAsync(DbConnection connection, UserOrderInsightsInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<UserOrderInsightsResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserOrderInsightsInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<UserOrderInsightsResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserOrderInsightsInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserOrderInsightsResult>(interceptorProvider, bindingProvider, connection, UserOrderInsightsPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, UserOrderInsightsInput input, Func<UserOrderInsightsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserOrderInsightsInput input, Func<UserOrderInsightsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, UserOrderInsightsInput input, Func<UserOrderInsightsResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "UserId");
            int o1=ReaderUtil.TryGetOrdinal(reader, "DisplayName");
            int o2=ReaderUtil.TryGetOrdinal(reader, "LatestOrderNumber");
            int o3=ReaderUtil.TryGetOrdinal(reader, "LatestOrderTotalAmount");
            int o4=ReaderUtil.TryGetOrdinal(reader, "LatestOrderCurrency");
            int o5=ReaderUtil.TryGetOrdinal(reader, "LatestOrderRequiredAtUtc");
            int o6=ReaderUtil.TryGetOrdinal(reader, "LatestOrderMetadata");
            int o7=ReaderUtil.TryGetOrdinal(reader, "PendingOrderCount");
            int o8=ReaderUtil.TryGetOrdinal(reader, "CapturedPaymentAmount");
            int o9=ReaderUtil.TryGetOrdinal(reader, "CapturedPaymentCount");
            int o10=ReaderUtil.TryGetOrdinal(reader, "NextContactReminderUtc");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new UserOrderInsightsResultSet1Result(o0 < 0 ? default(int) : reader.GetInt32(o0), o1 < 0 ? string.Empty : (reader.IsDBNull(o1) ? string.Empty : reader.GetString(o1)), o2 < 0 ? null : (reader.IsDBNull(o2) ? null : reader.GetString(o2)), o3 < 0 ? null : (reader.IsDBNull(o3) ? null : (decimal?)reader.GetDecimal(o3)), o4 < 0 ? null : (reader.IsDBNull(o4) ? null : reader.GetString(o4)), o5 < 0 ? null : (reader.IsDBNull(o5) ? null : (DateTime?)reader.GetDateTime(o5)), o6 < 0 ? null : (reader.IsDBNull(o6) ? null : reader.GetString(o6)), o7 < 0 ? null : (reader.IsDBNull(o7) ? null : (long?)reader.GetInt64(o7)), o8 < 0 ? null : (reader.IsDBNull(o8) ? null : (decimal?)reader.GetDecimal(o8)), o9 < 0 ? null : (reader.IsDBNull(o9) ? null : (Guid?)reader.GetGuid(o9)), o10 < 0 ? null : (reader.IsDBNull(o10) ? null : (DateTime?)reader.GetDateTime(o10)));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, UserOrderInsightsPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, UserOrderInsightsInput input, Func<UserOrderInsightsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, UserOrderInsightsInput input, Func<UserOrderInsightsResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
