// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Xtraq.Samples.RestApi.Xtraq;
using global::Xtraq.Samples.RestApi.Xtraq.Shared;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
#if NET8_0_OR_GREATER && XTRAQ_API_MODE_MINIMAL
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
#endif

namespace Xtraq.Samples.RestApi.Xtraq.Sample;

/// <summary>
/// Represents the contract for the stored procedure <c>sample.WriteAuditLogEntries</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for Minimal API / external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class WriteAuditLogEntriesRequest
{
    public IReadOnlyList<AuditLogEntryTableType>? Entries { get; init; }
}

public readonly record struct WriteAuditLogEntriesInput(
    IReadOnlyList<AuditLogEntryTableType>? Entries
);

public sealed class WriteAuditLogEntriesResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
}

internal static class WriteAuditLogEntriesRequestMapper
{
    public static async ValueTask<WriteAuditLogEntriesInput> ToInputAsync(WriteAuditLogEntriesRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new WriteAuditLogEntriesRequest();
        var Entries = request.Entries;
        if (!HasValue(Entries))
        {
            Entries = await ResolveTableAsync<AuditLogEntryTableType>(bindingProvider, "[sample].[WriteAuditLogEntries]", "@Entries", Entries, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Entries))
        {
            throw new InvalidOperationException("Parameter @Entries must be supplied by the request or a configured binding.");
        }

        return new WriteAuditLogEntriesInput(
            Entries
        );
    }

    public static ValueTask<WriteAuditLogEntriesInput> ToInputAsync(WriteAuditLogEntriesRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class WriteAuditLogEntriesPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Entries", System.Data.DbType.Object, null, false, false, "shared.AuditLogEntryTableType"),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new WriteAuditLogEntriesResult
			{
				Success = success,
				Error = error
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (WriteAuditLogEntriesInput)state!;
			{ var prm = cmd.Parameters["@Entries"]; var source = input.Entries; if (source != null) { var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; } if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "shared.AuditLogEntryTableType"; } }
		}
		return new ProcedureExecutionPlan(
			"[sample].[WriteAuditLogEntries]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[WriteAuditLogEntries]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class WriteAuditLogEntriesExtensions
{
    public static async Task<WriteAuditLogEntriesResult> WriteAuditLogEntriesAsync(this IXtraqDbContext db, WriteAuditLogEntriesRequest request, CancellationToken cancellationToken = default)
    {
        var bindingProvider = db as IXtraqParameterBindingProvider;
        var input = await WriteAuditLogEntriesRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
        return await WriteAuditLogEntriesAsync(db, input, cancellationToken).ConfigureAwait(false);
    }

	public static async Task<WriteAuditLogEntriesResult> WriteAuditLogEntriesAsync(this IXtraqDbContext db, WriteAuditLogEntriesInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await WriteAuditLogEntriesProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

#if NET8_0_OR_GREATER && XTRAQ_API_MODE_MINIMAL
/// <summary>Minimal API extension for '[sample].[WriteAuditLogEntries]'.</summary>
public static class WriteAuditLogEntriesRouteHandlerBuilderExtensions
{
    public static RouteHandlerBuilder WithWriteAuditLogEntriesProcedure(this RouteHandlerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithProcedure<WriteAuditLogEntriesRequest, WriteAuditLogEntriesResult>(
            static pipeline => pipeline.WithExecutor(
                static async ValueTask<WriteAuditLogEntriesResult> (dbContext, request, cancellationToken) =>
                {
                    var bindingProvider = dbContext as IXtraqParameterBindingProvider;
                    var input = await WriteAuditLogEntriesRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
                    return await WriteAuditLogEntriesExtensions.WriteAuditLogEntriesAsync(dbContext, input, cancellationToken).ConfigureAwait(false);
                }));
    }
}
#endif

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class WriteAuditLogEntriesProcedure
{
	public const string Name = "[sample].[WriteAuditLogEntries]";
	public static Task<WriteAuditLogEntriesResult> ExecuteAsync(DbConnection connection, WriteAuditLogEntriesInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<WriteAuditLogEntriesResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, WriteAuditLogEntriesInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<WriteAuditLogEntriesResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, WriteAuditLogEntriesInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<WriteAuditLogEntriesResult>(interceptorProvider, bindingProvider, connection, WriteAuditLogEntriesPlan.Instance, input, cancellationToken);
	}

}
