// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Sample;

using global::Xtraq.Samples.RestApi.Xtraq;
using global::Xtraq.Samples.RestApi.Xtraq.Shared;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
#if NET8_0_OR_GREATER && XTRAQ_MINIMAL_API
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
#endif

/// <summary>
/// Represents the contract for the stored procedure <c>sample.WriteAuditLogEntries</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
public readonly record struct WriteAuditLogEntriesInput(
    IReadOnlyList<AuditLogEntryTableType>? Entries
);

public sealed class WriteAuditLogEntriesResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
}

internal static partial class WriteAuditLogEntriesPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Entries", System.Data.DbType.Object, null, false, false, "shared.AuditLogEntryTableType"),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new WriteAuditLogEntriesResult
			{
				Success = success,
				Error = error
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (WriteAuditLogEntriesInput)state!;
			{ var prm = cmd.Parameters["@Entries"]; var source = input.Entries; if (source != null) { var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; } if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "shared.AuditLogEntryTableType"; } }
		}
		return new ProcedureExecutionPlan(
			"[sample].[WriteAuditLogEntries]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[sample].[WriteAuditLogEntries]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class WriteAuditLogEntriesExtensions
{
	public static async Task<WriteAuditLogEntriesResult> WriteAuditLogEntriesAsync(this IXtraqDbContext db, WriteAuditLogEntriesInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await WriteAuditLogEntriesProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

#if NET8_0_OR_GREATER && XTRAQ_MINIMAL_API
/// <summary>Minimal API extension for '[sample].[WriteAuditLogEntries]'.</summary>
public static class WriteAuditLogEntriesRouteHandlerBuilderExtensions
{
    public static RouteHandlerBuilder WithWriteAuditLogEntriesProcedure(this RouteHandlerBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithProcedure<WriteAuditLogEntriesInput, WriteAuditLogEntriesResult>(
            static pipeline => pipeline.WithExecutor(
                static (dbContext, input cancellationToken) => new ValueTask<WriteAuditLogEntriesResult>(
                    WriteAuditLogEntriesExtensions.WriteAuditLogEntriesAsync(dbContext, input, cancellationToken))));
    }
}
#endif

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class WriteAuditLogEntriesProcedure
{
	public const string Name = "[sample].[WriteAuditLogEntries]";
	public static Task<WriteAuditLogEntriesResult> ExecuteAsync(DbConnection connection, WriteAuditLogEntriesInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<WriteAuditLogEntriesResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, WriteAuditLogEntriesInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<WriteAuditLogEntriesResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, WriteAuditLogEntriesInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<WriteAuditLogEntriesResult>(interceptorProvider, bindingProvider, connection, WriteAuditLogEntriesPlan.Instance, input, cancellationToken);
	}

}
