using System;
using System.Collections.Generic;
using System.IO;
using Xtraq.Configuration;
using Xtraq.Engine;
using Xtraq.Generators;
using Xtraq.Metadata;
using Xunit;

namespace Xtraq.Tests;

public sealed class TableTypesGeneratorDependencyFilterTests
{
    [Fact]
    public void Generate_WhenDependenciesAreCatalogQualified_DoesNotFallbackToAllTableTypes()
    {
        var root = CreateWorkspace();
        try
        {
            var cfg = new XtraqConfiguration
            {
                NamespaceRoot = "Test.Namespace",
                OutputDir = "Xtraq",
                ProjectRoot = root
            };

            var provider = new InMemoryTableTypeMetadataProvider(new[]
            {
                CreateType("core", "Context"),
                CreateType("acquisition", "TalkPartnerTableType"),
                CreateType("calendar", "HolidayType")
            });

            var renderer = new SimpleTemplateEngine();
            var loader = new EmbeddedResourceTemplateLoader(typeof(TableTypesGenerator).Assembly, "Xtraq.Templates.");
            var generator = new TableTypesGenerator(cfg, provider, renderer, loader, root);

            var requiredReferences = new[]
            {
                "GeneratorDb.core.Context",
                "GeneratorDb.acquisition.TalkPartnerTableType"
            };

            var result = generator.Generate(requiredReferences);

            Assert.Contains("Core", result.ArtifactsPerSchema.Keys);
            Assert.Contains("Acquisition", result.ArtifactsPerSchema.Keys);
            Assert.DoesNotContain("Calendar", result.ArtifactsPerSchema.Keys);

            Assert.True(File.Exists(Path.Combine(root, "Xtraq", "Core", "Context.cs")));
            Assert.True(File.Exists(Path.Combine(root, "Xtraq", "Acquisition", "TalkPartnerTableType.cs")));
            Assert.False(File.Exists(Path.Combine(root, "Xtraq", "Calendar", "HolidayType.cs")));
        }
        finally
        {
            TryDeleteDirectory(root);
        }
    }

    [Fact]
    public void Generate_RemovesStaleGeneratedTableTypeArtifactsWithinRetainedSchema()
    {
        var root = CreateWorkspace();
        try
        {
            var coreDir = Path.Combine(root, "Xtraq", "Core");
            Directory.CreateDirectory(coreDir);
            var staleFile = Path.Combine(coreDir, "ComparisonCalculationType.cs");
            File.WriteAllText(
                staleFile,
                "// <auto-generated/>\n// generated\n/// Provides a strongly typed projection over the SQL table type <c>Core.ComparisonCalculationType</c>.\npublic sealed record ComparisonCalculationType : ITableType;\n");

            var cfg = new XtraqConfiguration
            {
                NamespaceRoot = "Test.Namespace",
                OutputDir = "Xtraq",
                ProjectRoot = root
            };

            var provider = new InMemoryTableTypeMetadataProvider(new[]
            {
                CreateType("core", "Context")
            });

            var renderer = new SimpleTemplateEngine();
            var loader = new EmbeddedResourceTemplateLoader(typeof(TableTypesGenerator).Assembly, "Xtraq.Templates.");
            var generator = new TableTypesGenerator(cfg, provider, renderer, loader, root);

            var result = generator.Generate(new[] { "core.Context" });

            Assert.Contains("Core", result.ArtifactsPerSchema.Keys);
            Assert.True(File.Exists(Path.Combine(root, "Xtraq", "Core", "Context.cs")));
            Assert.False(File.Exists(staleFile));
        }
        finally
        {
            TryDeleteDirectory(root);
        }
    }

    private static TableTypeInfo CreateType(string schema, string name)
    {
        return new TableTypeInfo
        {
            Schema = schema,
            Name = name,
            Columns = new[]
            {
                new ColumnInfo
                {
                    Name = "Value",
                    SqlType = "nvarchar(100)",
                    TypeRef = "sys.nvarchar",
                    IsNullable = true,
                    MaxLength = 100
                }
            }
        };
    }

    private static string CreateWorkspace()
    {
        var path = Path.Combine(Path.GetTempPath(), "xtraq-tabletypes-generator-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(path);
        return path;
    }

    private static void TryDeleteDirectory(string path)
    {
        try
        {
            if (Directory.Exists(path))
            {
                Directory.Delete(path, recursive: true);
            }
        }
        catch
        {
            // best-effort cleanup
        }
    }

    private sealed class InMemoryTableTypeMetadataProvider : ITableTypeMetadataProvider
    {
        private readonly IReadOnlyList<TableTypeInfo> _tableTypes;

        public InMemoryTableTypeMetadataProvider(IReadOnlyList<TableTypeInfo> tableTypes)
        {
            _tableTypes = tableTypes ?? Array.Empty<TableTypeInfo>();
        }

        public IReadOnlyList<TableTypeInfo> GetAll() => _tableTypes;
    }
}
