// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;
#if XTRAQ_ENABLE_TABLETYPE_VALIDATION
using FluentValidation;
#endif

namespace Xtraq.Samples.RestApi.Xtraq.Shared;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Shared.AuditLogEntryTableType</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record AuditLogEntryTableType : ITableType
{
#if XTRAQ_ENFORCE_TABLETYPE_BUILDER
	#warning Use the 'AuditLogEntryTableTypeBuilder' or factory method instead of object initializers.
#endif

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public AuditLogEntryTableType() { }

	public static AuditLogEntryTableType Create(
    ) =>
	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
	new AuditLogEntryTableType
	{
    };
	#pragma warning restore CS0612, CS0618

	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class AuditLogEntryTableTypeBuilder
	{
        public AuditLogEntryTableType Build()
        {
			#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
			var result = new AuditLogEntryTableType
            {
            };
			#pragma warning restore CS0612, CS0618
#if XTRAQ_ENABLE_TABLETYPE_VALIDATION
            AuditLogEntryTableTypeValidator.Instance.ValidateAndThrow(result);
#endif
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
#if XTRAQ_ENABLE_TABLETYPE_VALIDATION
	private sealed class AuditLogEntryTableTypeValidator : AbstractValidator<AuditLogEntryTableType>
	{
		public static readonly AuditLogEntryTableTypeValidator Instance = new();
		public AuditLogEntryTableTypeValidator()
		{
			// Add rules (placeholder - extend generator to emit rules per column metadata, e.g. nullability / max length)
			// Example: RuleFor(x => x.SomeColumn).NotNull();
		}
	}
#endif
}
