// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq.Shared;

using System;
#if XTRAQ_ENABLE_TABLETYPE_VALIDATION
using FluentValidation;
#endif

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Shared.AuditLogEntryTableType</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record AuditLogEntryTableType : ITableType
{
    public string Source { get; init; } = string.Empty;
    public string Message { get; init; } = string.Empty;
    public byte Severity { get; init; }
    public Guid? CorrelationId { get; init; }
    public string? Details { get; init; }
#if XTRAQ_ENFORCE_TABLETYPE_BUILDER
	#warning Use the 'AuditLogEntryTableTypeBuilder' or factory method instead of object initializers.
#endif

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public AuditLogEntryTableType() { }

	public static AuditLogEntryTableType Create(
        string Source,
        string Message,
        byte Severity,
        Guid? CorrelationId,
        string? Details
    ) =>
	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
	new AuditLogEntryTableType
	{
        Source = Source,
        Message = Message,
        Severity = Severity,
        CorrelationId = CorrelationId,
        Details = Details
    };
	#pragma warning restore CS0612, CS0618

	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class AuditLogEntryTableTypeBuilder
	{
        private string _Source = string.Empty;
        private string _Message = string.Empty;
        private byte _Severity;
        private Guid? _CorrelationId;
        private string? _Details;
        public AuditLogEntryTableTypeBuilder WithSource(string value) { _Source = value; return this; }
        public AuditLogEntryTableTypeBuilder WithMessage(string value) { _Message = value; return this; }
        public AuditLogEntryTableTypeBuilder WithSeverity(byte value) { _Severity = value; return this; }
        public AuditLogEntryTableTypeBuilder WithCorrelationId(Guid? value) { _CorrelationId = value; return this; }
        public AuditLogEntryTableTypeBuilder WithDetails(string? value) { _Details = value; return this; }
        public AuditLogEntryTableType Build()
        {
			#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
			var result = new AuditLogEntryTableType
            {
                Source = _Source,
                Message = _Message,
                Severity = _Severity,
                CorrelationId = _CorrelationId,
                Details = _Details
            };
			#pragma warning restore CS0612, CS0618
#if XTRAQ_ENABLE_TABLETYPE_VALIDATION
            AuditLogEntryTableTypeValidator.Instance.ValidateAndThrow(result);
#endif
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
#if XTRAQ_ENABLE_TABLETYPE_VALIDATION
	private sealed class AuditLogEntryTableTypeValidator : AbstractValidator<AuditLogEntryTableType>
	{
		public static readonly AuditLogEntryTableTypeValidator Instance = new();
		public AuditLogEntryTableTypeValidator()
		{
			// Add rules (placeholder - extend generator to emit rules per column metadata, e.g. nullability / max length)
			// Example: RuleFor(x => x.SomeColumn).NotNull();
		}
	}
#endif
}
