// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Xtraq.Samples.RestApi.Xtraq.Shared;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Shared.AuditLogEntryTableType</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record AuditLogEntryTableType : ITableType
{
    public string Source { get; init; } = string.Empty;
    public string Message { get; init; } = string.Empty;
    public byte Severity { get; init; }
    public Guid? CorrelationId { get; init; }
    public string? Details { get; init; }

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public AuditLogEntryTableType() { }

	public static AuditLogEntryTableType Create(
        string Source,
        string Message,
        byte Severity,
        Guid? CorrelationId,
        string? Details
    ) =>
	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
	new AuditLogEntryTableType
	{
        Source = Source,
        Message = Message,
        Severity = Severity,
        CorrelationId = CorrelationId,
        Details = Details
    };
	#pragma warning restore CS0612, CS0618

	#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class AuditLogEntryTableTypeBuilder
	{
        private string _Source = string.Empty;
        private string _Message = string.Empty;
        private byte _Severity;
        private Guid? _CorrelationId;
        private string? _Details;
        public AuditLogEntryTableTypeBuilder WithSource(string value) { _Source = value; return this; }
        public AuditLogEntryTableTypeBuilder WithMessage(string value) { _Message = value; return this; }
        public AuditLogEntryTableTypeBuilder WithSeverity(byte value) { _Severity = value; return this; }
        public AuditLogEntryTableTypeBuilder WithCorrelationId(Guid? value) { _CorrelationId = value; return this; }
        public AuditLogEntryTableTypeBuilder WithDetails(string? value) { _Details = value; return this; }
        public AuditLogEntryTableType Build()
        {
			#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
			var result = new AuditLogEntryTableType
            {
                Source = _Source,
                Message = _Message,
                Severity = _Severity,
                CorrelationId = _CorrelationId,
                Details = _Details
            };
			#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

/// <summary>
/// Minimal API request row mirroring the SQL table type <c>Shared.AuditLogEntryTableType</c> with DataAnnotations metadata.
/// </summary>
public sealed record AuditLogEntryTableTypeRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(120)]
    public string Source { get; init; }
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(4000)]
    public string Message { get; init; }
    public byte Severity { get; init; }
    public Guid? CorrelationId { get; init; }
    public string? Details { get; init; }

	internal AuditLogEntryTableType ToTableType()
		=> AuditLogEntryTableType.Create(
            Source,
            Message,
            Severity,
            CorrelationId,
            Details
        );

	internal static System.Collections.Generic.IReadOnlyList<AuditLogEntryTableType>? ToTableTypes(System.Collections.Generic.IReadOnlyList<AuditLogEntryTableTypeRequest>? source)
	{
		if (source is null) return null;
		if (source.Count == 0) return System.Array.Empty<AuditLogEntryTableType>();
		var buffer = new AuditLogEntryTableType[source.Count];
		for (var i = 0; i < source.Count; i++)
		{
			var row = source[i];
			if (row is null)
			{
				throw new System.InvalidOperationException("Table type rows cannot contain null entries.");
			}

			buffer[i] = row.ToTableType();
		}

		return buffer;
	}
}
