// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq;

using System;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Runs callbacks on success/failure to record history or wrap results without changing executor signatures.
/// </summary>
public sealed class HistoryExecutionPolicy<TInput, TResult> : IProcedureExecutionPolicy
{
    private readonly Func<ProcedureExecutionContext<TInput>, TResult, CancellationToken, ValueTask> _onSuccess;
    private readonly Func<ProcedureExecutionContext<TInput>, Exception, CancellationToken, ValueTask>? _onFailure;

    public HistoryExecutionPolicy(
        Func<ProcedureExecutionContext<TInput>, TResult, CancellationToken, ValueTask> onSuccess,
        Func<ProcedureExecutionContext<TInput>, Exception, CancellationToken, ValueTask>? onFailure = null)
    {
        _onSuccess = onSuccess ?? throw new ArgumentNullException(nameof(onSuccess));
        _onFailure = onFailure;
    }

    public HistoryExecutionPolicy(
        Func<ProcedureExecutionContext<TInput>, TResult, Task> onSuccess,
        Func<ProcedureExecutionContext<TInput>, Exception, Task>? onFailure = null)
    {
        if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));
        _onSuccess = (ctx, result, _) => new ValueTask(onSuccess(ctx, result));
        _onFailure = onFailure is null ? null : (ctx, ex, _) => new ValueTask(onFailure(ctx, ex));
    }

    public async ValueTask<TOut> ExecuteAsync<TIn, TOut>(
        ProcedureExecutionContext<TIn> context,
        ProcedureCallDelegate<TIn, TOut> next,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(next);

        var isTarget = typeof(TIn) == typeof(TInput) && typeof(TOut) == typeof(TResult);
        if (!isTarget)
        {
            return await next(context, cancellationToken).ConfigureAwait(false);
        }

        try
        {
            var result = await next(context, cancellationToken).ConfigureAwait(false);
            await _onSuccess(Rewrap(context), (TResult)(object)result!, cancellationToken).ConfigureAwait(false);
            return result;
        }
        catch (Exception ex)
        {
            if (_onFailure is not null)
            {
                await _onFailure(Rewrap(context), ex, cancellationToken).ConfigureAwait(false);
            }
            throw;
        }
    }

    private static ProcedureExecutionContext<TInput> Rewrap<TIn>(ProcedureExecutionContext<TIn> context)
    {
        var baseContext = (IProcedureExecutionContext)context;
        return new ProcedureExecutionContext<TInput>(
            context.DbContext,
            (TInput)baseContext.InputValue!,
            baseContext.Label,
            context.TransactionOrchestrator);
    }
}
