// <auto-generated/>
// Xtraq Code Generator v1.0.0-alpha.6. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

namespace Xtraq.Samples.RestApi.Xtraq;

public interface ITableType {}
