// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq;

using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

/// <summary>Provides scoped procedure interceptors that supplement the globally registered instances.</summary>
public interface IXtraqProcedureInterceptorProvider
{
    /// <summary>Gets the interceptors that should observe the upcoming procedure execution.</summary>
    IReadOnlyList<IXtraqProcedureInterceptor> GetInterceptors();
}

/// <summary>Intercepts low-level procedure execution to capture telemetry or inject side effects.</summary>
public interface IXtraqProcedureInterceptor
{
    /// <summary>Called before the command executes. Return a state object that will be passed into <see cref="OnAfterExecuteAsync"/>.</summary>
    Task<object?> OnBeforeExecuteAsync(string procedureName, DbCommand command, object? state, CancellationToken cancellationToken);

    /// <summary>Called once the command finished executing (success or failure).</summary>
    Task OnAfterExecuteAsync(string procedureName, DbCommand command, bool success, string? error, System.TimeSpan duration, object? beforeState, object? aggregate, CancellationToken cancellationToken);
}
