// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq;

using System;
using System.Runtime.ExceptionServices;
using System.Threading;
using System.Threading.Tasks;

public delegate XtraqTransactionOptions? TransactionOptionsSelector<TInput>(ProcedureExecutionContext<TInput> context);

public sealed class TransactionScopeExecutionPolicy : IProcedureExecutionPolicy
{
    private readonly Func<IProcedureExecutionContext, XtraqTransactionOptions?>? _optionsFactory;

    public TransactionScopeExecutionPolicy()
    {
    }

    public TransactionScopeExecutionPolicy(XtraqTransactionOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        _optionsFactory = _ => options;
    }

    public TransactionScopeExecutionPolicy(Func<IProcedureExecutionContext, XtraqTransactionOptions?> optionsFactory)
    {
        _optionsFactory = optionsFactory ?? throw new ArgumentNullException(nameof(optionsFactory));
    }

    public async ValueTask<TResult> ExecuteAsync<TInput, TResult>(
        ProcedureExecutionContext<TInput> context,
        ProcedureCallDelegate<TInput, TResult> next,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(next);

        var options = _optionsFactory?.Invoke(context);
        await using var scope = await context.TransactionOrchestrator.BeginAsync(options, cancellationToken).ConfigureAwait(false);
        try
        {
            var result = await next(context, cancellationToken).ConfigureAwait(false);
            await scope.CommitAsync(cancellationToken).ConfigureAwait(false);
            return result;
        }
        catch (Exception ex)
        {
            Exception? rollbackException = null;
            try
            {
                await scope.RollbackAsync(cancellationToken).ConfigureAwait(false);
            }
            catch (Exception rollbackEx)
            {
                rollbackException = rollbackEx;
            }

            if (rollbackException is not null)
            {
                throw new AggregateException(ex, rollbackException);
            }

            ExceptionDispatchInfo.Capture(ex).Throw();
            throw;
        }
    }
}

public static class TransactionScopeExecutionPolicyFactory
{
    public static TransactionScopeExecutionPolicy Default { get; } = new();

    public static TransactionScopeExecutionPolicy FromOptions(XtraqTransactionOptions options)
        => new(options);

    public static TransactionScopeExecutionPolicy FromSelector(Func<IProcedureExecutionContext, XtraqTransactionOptions?> selector)
        => new(selector);

    public static TransactionScopeExecutionPolicy FromSelector<TInput>(TransactionOptionsSelector<TInput> selector)
    {
        ArgumentNullException.ThrowIfNull(selector);
        return new(context => selector((ProcedureExecutionContext<TInput>)context));
    }
}
