// <auto-generated/>
// . This file is generated; do not edit directly.
// Customize via additional partial classes or extension templates.
#nullable enable
namespace Xtraq.Samples.RestApi.Xtraq;

using System;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;

/// <summary>Generated database context providing ADO.NET connection helpers and health probe.</summary>
public sealed partial class XtraqDbContext : IXtraqDbContext, IXtraqTransactionOrchestratorAccessor
{
    private readonly XtraqDbContextOptions _options;
    private readonly IServiceProvider? _serviceProvider;
    private IXtraqTransactionOrchestrator? _transactionOrchestrator;

    public XtraqDbContext(XtraqDbContextOptions options, IServiceProvider? serviceProvider = null)
    {
        _options = options ?? throw new ArgumentNullException(nameof(options));
        _serviceProvider = serviceProvider;
        if (string.IsNullOrWhiteSpace(_options.ConnectionString))
            throw new InvalidOperationException("XtraqDbContextOptions.ConnectionString must be set.");
        if (_options.CommandTimeout == null || _options.CommandTimeout < 1)
            _options.CommandTimeout = 30;
    }

    /// <inheritdoc />
    public int CommandTimeout => _options.CommandTimeout ?? 30;

    /// <inheritdoc />
    public DbConnection OpenConnection()
    {
        var conn = new SqlConnection(_options.ConnectionString);
        conn.Open();
        return conn;
    }

    /// <inheritdoc />
    public async Task<DbConnection> OpenConnectionAsync(CancellationToken cancellationToken = default)
    {
        var conn = new SqlConnection(_options.ConnectionString);
        await conn.OpenAsync(cancellationToken).ConfigureAwait(false);
        return conn;
    }

    /// <inheritdoc />
    public async Task<bool> HealthCheckAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            await using var conn = new SqlConnection(_options.ConnectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);
            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>Resolves the scoped transaction orchestrator associated with this context.</summary>
    public IXtraqTransactionOrchestrator TransactionOrchestrator
    {
        get
        {
            if (_transactionOrchestrator is not null)
            {
                return _transactionOrchestrator;
            }

            if (_serviceProvider is not null)
            {
                var resolved = _serviceProvider.GetService<IXtraqTransactionOrchestrator>();
                if (resolved is not null)
                {
                    _transactionOrchestrator = resolved;
                    return resolved;
                }
            }

            var fallback = new XtraqTransactionOrchestrator(this);
            _transactionOrchestrator = fallback;
            return fallback;
        }
    }
}
